packages:
  - src/backend-api
  - src/backend-tests
  - src/canister-history-api
  - src/canister-history-tests
  - src/frontend
  - src/management-canister
  - src/sync-subnet-canister-ranges

onlyBuiltDependencies:
  - '@dfinity/pic'
  - '@parcel/watcher'
  - esbuild
