// Package history provides a client for the "canisterHistory" canister.
// Do NOT edit this file. It was automatically generated by https://github.com/aviate-labs/agent-go.
package history

import (
    "github.com/aviate-labs/agent-go"
    "github.com/aviate-labs/agent-go/principal"
)

type PaginationMetaResponse struct {
	Limit      uint64 `ic:"limit" json:"limit"`
	Page       uint64 `ic:"page" json:"page"`
	TotalItems uint64 `ic:"total_items" json:"total_items"`
	TotalPages uint64 `ic:"total_pages" json:"total_pages"`
}

type UpdateSubnetCanisterRangesRequest struct {
	CanisterRanges []struct {
	Field0 principal.Principal `ic:"0,tuple" json:"0"`
	Field1 principal.Principal `ic:"1,tuple" json:"1"`
} `ic:"canister_ranges" json:"canister_ranges"`
}

type UpdateSubnetCanisterRangesResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type ListSubnetCanisterRangesRequest struct {
}

type ListSubnetCanisterRangesResponse struct {
	Ok  *struct {
	CanisterRanges []struct {
	Field0 principal.Principal `ic:"0,tuple" json:"0"`
	Field1 principal.Principal `ic:"1,tuple" json:"1"`
} `ic:"canister_ranges" json:"canister_ranges"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                            `ic:"Err,variant" json:"Err,omitempty"`
}

type ListSubnetCanisterIdsRequest struct {
}

type ListSubnetCanisterIdsResponse struct {
	Ok  *struct {
	CanisterIdRanges []struct {
	Field0 principal.Principal `ic:"0,tuple" json:"0"`
	Field1 principal.Principal `ic:"1,tuple" json:"1"`
} `ic:"canister_id_ranges" json:"canister_id_ranges"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                              `ic:"Err,variant" json:"Err,omitempty"`
}

type ListKnownCanistersRequest struct {
}

type KnownCanister struct {
	CanisterId principal.Principal `ic:"canister_id" json:"canister_id"`
	IsDeleted  bool                `ic:"is_deleted" json:"is_deleted"`
}

type ListKnownCanistersResponse struct {
	Ok  *struct {
	Canisters []KnownCanister `ic:"canisters" json:"canisters"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                     `ic:"Err,variant" json:"Err,omitempty"`
}

type ListCanisterChangesRequest struct {
	CanisterId principal.Principal `ic:"canister_id" json:"canister_id"`
	Reverse    *bool               `ic:"reverse,omitempty" json:"reverse,omitempty"`
	Limit      *uint64             `ic:"limit,omitempty" json:"limit,omitempty"`
	Page       *uint64             `ic:"page,omitempty" json:"page,omitempty"`
}

type ListCanisterChangesResponse struct {
	Ok  *struct {
	Changes   []CanisterChange       `ic:"changes" json:"changes"`
	IsDeleted bool                   `ic:"is_deleted" json:"is_deleted"`
	Meta      PaginationMetaResponse `ic:"meta" json:"meta"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                              `ic:"Err,variant" json:"Err,omitempty"`
}

type TriggerSyncCanisterHistoriesRequest struct {
}

type TriggerSyncCanisterHistoriesResponse struct {
	Ok  *struct {
	Message string `ic:"message" json:"message"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                      `ic:"Err,variant" json:"Err,omitempty"`
}

type CanisterChangeOrigin struct {
	FromUser     *struct {
	UserId principal.Principal `ic:"user_id" json:"user_id"`
}                                     `ic:"FromUser,variant" json:"FromUser,omitempty"`
	FromCanister *struct {
	CanisterId      principal.Principal `ic:"canister_id" json:"canister_id"`
	CanisterVersion *uint64             `ic:"canister_version,omitempty" json:"canister_version,omitempty"`
} `ic:"FromCanister,variant" json:"FromCanister,omitempty"`
}

type CanisterChangeDetails struct {
	Creation          *struct {
	Controllers              []principal.Principal `ic:"controllers" json:"controllers"`
	EnvironmentVariablesHash *[]byte               `ic:"environment_variables_hash,omitempty" json:"environment_variables_hash,omitempty"`
} `ic:"Creation,variant" json:"Creation,omitempty"`
	CodeUninstall     *struct {
}                                                                                                                              `ic:"CodeUninstall,variant" json:"CodeUninstall,omitempty"`
	CodeDeployment    *struct {
	Mode       *CodeDeploymentMode `ic:"mode,omitempty" json:"mode,omitempty"`
	ModuleHash []byte              `ic:"module_hash" json:"module_hash"`
} `ic:"CodeDeployment,variant" json:"CodeDeployment,omitempty"`
	LoadSnapshot      *struct {
	FromCanisterId   *principal.Principal `ic:"from_canister_id,omitempty" json:"from_canister_id,omitempty"`
	SnapshotId       []byte               `ic:"snapshot_id" json:"snapshot_id"`
	CanisterVersion  uint64               `ic:"canister_version" json:"canister_version"`
	TakenAtTimestamp uint64               `ic:"taken_at_timestamp" json:"taken_at_timestamp"`
	Source           *SnapshotSource      `ic:"source,omitempty" json:"source,omitempty"`
} `ic:"LoadSnapshot,variant" json:"LoadSnapshot,omitempty"`
	ControllersChange *struct {
	Controllers []principal.Principal `ic:"controllers" json:"controllers"`
}                                                     `ic:"ControllersChange,variant" json:"ControllersChange,omitempty"`
}

type CodeDeploymentMode struct {
	Install   *struct {
} `ic:"Install,variant" json:"Install,omitempty"`
	Reinstall *struct {
} `ic:"Reinstall,variant" json:"Reinstall,omitempty"`
	Upgrade   *struct {
} `ic:"Upgrade,variant" json:"Upgrade,omitempty"`
}

type SnapshotSource struct {
	TakenFromCanister *struct {
} `ic:"TakenFromCanister,variant" json:"TakenFromCanister,omitempty"`
	MetadataUpload    *struct {
} `ic:"MetadataUpload,variant" json:"MetadataUpload,omitempty"`
}

type CanisterChange struct {
	Id              string                 `ic:"id" json:"id"`
	CanisterId      principal.Principal    `ic:"canister_id" json:"canister_id"`
	TimestampNanos  uint64                 `ic:"timestamp_nanos" json:"timestamp_nanos"`
	CanisterVersion uint64                 `ic:"canister_version" json:"canister_version"`
	Origin          *CanisterChangeOrigin  `ic:"origin,omitempty" json:"origin,omitempty"`
	Details         *CanisterChangeDetails `ic:"details,omitempty" json:"details,omitempty"`
}

type ApiError struct {
	Code    *ApiErrorCode `ic:"code,omitempty" json:"code,omitempty"`
	Message string        `ic:"message" json:"message"`
}

type ApiErrorCode struct {
	Unauthenticated *struct {
} `ic:"Unauthenticated,variant" json:"Unauthenticated,omitempty"`
	Unauthorized    *struct {
} `ic:"Unauthorized,variant" json:"Unauthorized,omitempty"`
	DependencyError *struct {
} `ic:"DependencyError,variant" json:"DependencyError,omitempty"`
	InternalError   *struct {
} `ic:"InternalError,variant" json:"InternalError,omitempty"`
	ClientError     *struct {
} `ic:"ClientError,variant" json:"ClientError,omitempty"`
	QuotaExceeded   *struct {
} `ic:"QuotaExceeded,variant" json:"QuotaExceeded,omitempty"`
}

// CanisterHistoryAgent is a client for the "canisterHistory" canister.
type CanisterHistoryAgent struct {
    *agent.Agent
    CanisterId principal.Principal
}

// NewCanisterHistoryAgent creates a new agent for the "canisterHistory" canister.
func NewCanisterHistoryAgent(canisterId principal.Principal, config agent.Config) (*CanisterHistoryAgent, error) {
    a, err := agent.New(config)
    if err != nil {
        return nil, err
    }
    return &CanisterHistoryAgent{
        Agent:      a,
        CanisterId: canisterId,
    }, nil
}

// UpdateSubnetCanisterRanges calls the "update_subnet_canister_ranges" method on the "canisterHistory" canister.
func (a CanisterHistoryAgent) UpdateSubnetCanisterRanges(arg0 UpdateSubnetCanisterRangesRequest) (*UpdateSubnetCanisterRangesResponse, error) {
    var r0 UpdateSubnetCanisterRangesResponse
    if err := a.Call(
        a.CanisterId,
        "update_subnet_canister_ranges",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListSubnetCanisterRanges calls the "list_subnet_canister_ranges" method on the "canisterHistory" canister.
func (a CanisterHistoryAgent) ListSubnetCanisterRanges(arg0 ListSubnetCanisterRangesRequest) (*ListSubnetCanisterRangesResponse, error) {
    var r0 ListSubnetCanisterRangesResponse
    if err := a.Query(
        a.CanisterId,
        "list_subnet_canister_ranges",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListSubnetCanisterIds calls the "list_subnet_canister_ids" method on the "canisterHistory" canister.
func (a CanisterHistoryAgent) ListSubnetCanisterIds(arg0 ListSubnetCanisterIdsRequest) (*ListSubnetCanisterIdsResponse, error) {
    var r0 ListSubnetCanisterIdsResponse
    if err := a.Query(
        a.CanisterId,
        "list_subnet_canister_ids",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListKnownCanisters calls the "list_known_canisters" method on the "canisterHistory" canister.
func (a CanisterHistoryAgent) ListKnownCanisters(arg0 ListKnownCanistersRequest) (*ListKnownCanistersResponse, error) {
    var r0 ListKnownCanistersResponse
    if err := a.Query(
        a.CanisterId,
        "list_known_canisters",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListCanisterChanges calls the "list_canister_changes" method on the "canisterHistory" canister.
func (a CanisterHistoryAgent) ListCanisterChanges(arg0 ListCanisterChangesRequest) (*ListCanisterChangesResponse, error) {
    var r0 ListCanisterChangesResponse
    if err := a.Query(
        a.CanisterId,
        "list_canister_changes",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// TriggerSyncCanisterHistories calls the "trigger_sync_canister_histories" method on the "canisterHistory" canister.
func (a CanisterHistoryAgent) TriggerSyncCanisterHistories(arg0 TriggerSyncCanisterHistoriesRequest) (*TriggerSyncCanisterHistoriesResponse, error) {
    var r0 TriggerSyncCanisterHistoriesResponse
    if err := a.Call(
        a.CanisterId,
        "trigger_sync_canister_histories",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}
