// Package cyclesmonitor provides a client for the "cyclesmonitor" canister.
// Do NOT edit this file. It was automatically generated by https://github.com/aviate-labs/agent-go.
package cyclesmonitor

import (
    "github.com/aviate-labs/agent-go"
    "github.com/aviate-labs/agent-go/candid/idl"
    "github.com/aviate-labs/agent-go/principal"
)

type TriggerSyncMetricsRequest struct {
}

type TriggerSyncMetricsResponse struct {
	Ok  *struct {
	Message string `ic:"message" json:"message"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                      `ic:"Err,variant" json:"Err,omitempty"`
}

type ListMetricsAfterRequest struct {
	Cursor *Cursor `ic:"cursor,omitempty" json:"cursor,omitempty"`
}

type CyclesMetricsSnapshotDto struct {
	TimestampNs                    uint64              `ic:"timestamp_ns" json:"timestamp_ns"`
	CanisterId                     principal.Principal `ic:"canister_id" json:"canister_id"`
	Memory                         idl.Nat             `ic:"memory" json:"memory"`
	ComputeAllocation              idl.Nat             `ic:"compute_allocation" json:"compute_allocation"`
	IngressInduction               idl.Nat             `ic:"ingress_induction" json:"ingress_induction"`
	Instructions                   idl.Nat             `ic:"instructions" json:"instructions"`
	RequestAndResponseTransmission idl.Nat             `ic:"request_and_response_transmission" json:"request_and_response_transmission"`
	Uninstall                      idl.Nat             `ic:"uninstall" json:"uninstall"`
	HttpOutcalls                   idl.Nat             `ic:"http_outcalls" json:"http_outcalls"`
	BurnedCycles                   idl.Nat             `ic:"burned_cycles" json:"burned_cycles"`
}

type ListMetricsAfterResponse struct {
	Ok  *struct {
	Snapshots  []CyclesMetricsSnapshotDto `ic:"snapshots" json:"snapshots"`
	NextCursor *Cursor                    `ic:"next_cursor,omitempty" json:"next_cursor,omitempty"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                                                         `ic:"Err,variant" json:"Err,omitempty"`
}

type Cursor struct {
	Field0 uint64              `ic:"0,tuple" json:"0"`
	Field1 principal.Principal `ic:"1,tuple" json:"1"`
}

type ApiError struct {
	Code    *ApiErrorCode `ic:"code,omitempty" json:"code,omitempty"`
	Message string        `ic:"message" json:"message"`
}

type ApiErrorCode struct {
	Unauthenticated *struct {
} `ic:"Unauthenticated,variant" json:"Unauthenticated,omitempty"`
	Unauthorized    *struct {
} `ic:"Unauthorized,variant" json:"Unauthorized,omitempty"`
	DependencyError *struct {
} `ic:"DependencyError,variant" json:"DependencyError,omitempty"`
	InternalError   *struct {
} `ic:"InternalError,variant" json:"InternalError,omitempty"`
	ClientError     *struct {
} `ic:"ClientError,variant" json:"ClientError,omitempty"`
	QuotaExceeded   *struct {
} `ic:"QuotaExceeded,variant" json:"QuotaExceeded,omitempty"`
}

// CyclesmonitorAgent is a client for the "cyclesmonitor" canister.
type CyclesmonitorAgent struct {
    *agent.Agent
    CanisterId principal.Principal
}

// NewCyclesmonitorAgent creates a new agent for the "cyclesmonitor" canister.
func NewCyclesmonitorAgent(canisterId principal.Principal, config agent.Config) (*CyclesmonitorAgent, error) {
    a, err := agent.New(config)
    if err != nil {
        return nil, err
    }
    return &CyclesmonitorAgent{
        Agent:      a,
        CanisterId: canisterId,
    }, nil
}

// TriggerSyncMetrics calls the "trigger_sync_metrics" method on the "cyclesmonitor" canister.
func (a CyclesmonitorAgent) TriggerSyncMetrics(arg0 TriggerSyncMetricsRequest) (*TriggerSyncMetricsResponse, error) {
    var r0 TriggerSyncMetricsResponse
    if err := a.Call(
        a.CanisterId,
        "trigger_sync_metrics",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListMetricsAfter calls the "list_metrics_after" method on the "cyclesmonitor" canister.
func (a CyclesmonitorAgent) ListMetricsAfter(arg0 ListMetricsAfterRequest) (*ListMetricsAfterResponse, error) {
    var r0 ListMetricsAfterResponse
    if err := a.Call(
        a.CanisterId,
        "list_metrics_after",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}
