// Pending link codes live in heap, not stable memory: single-use bearer
// tokens, losing them on upgrade just means the user generates a new one.
//
// Codes are generated by the frontend (browser CSPRNG). The backend owns
// the binding and the single-use guarantee. Standard OAuth-`state` pattern.
//
// At most one pending code per user; registering replaces any existing one.

use crate::data::{user_profile_repository, LinkedPrincipal, StaffPermissions};
use crate::service::access_control_service;
use crate::validation::validate_optional_principal_name;
use candid::Principal;
use canister_utils::{now_nanos, ApiError, ApiResult, Uuid};
use std::cell::RefCell;
use std::collections::HashMap;

const LINK_CODE_TTL_NANOS: u64 = 15 * 60 * 1_000_000_000;
const LINK_CODE_LEN: usize = 8;

thread_local! {
    static PENDING_LINK_CODES: RefCell<HashMap<Uuid, PendingLinkCode>> = RefCell::new(HashMap::new());
}

#[derive(Clone)]
struct PendingLinkCode {
    code: String,
    target_principal: Principal,
    expires_at_nanos: u64,
}

#[derive(Debug)]
pub struct RegisteredLinkCode {
    pub expires_at_nanos: u64,
}

pub fn register_link_code(
    caller: &Principal,
    code: String,
    target_principal: Principal,
) -> ApiResult<RegisteredLinkCode> {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    validate_code_format(&code)?;

    if target_principal == Principal::anonymous() {
        return Err(ApiError::client_error(
            "Target principal must not be anonymous.".to_string(),
        ));
    }

    let now = now_nanos();
    let expires_at = now.saturating_add(LINK_CODE_TTL_NANOS);

    PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        codes.retain(|_, v| v.expires_at_nanos > now);
        codes.insert(
            user_id,
            PendingLinkCode {
                code,
                target_principal,
                expires_at_nanos: expires_at,
            },
        );
    });

    Ok(RegisteredLinkCode {
        expires_at_nanos: expires_at,
    })
}

pub fn link_my_principal(caller: &Principal, code: String) -> ApiResult {
    let now = now_nanos();

    let user_id = PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        codes.retain(|_, v| v.expires_at_nanos > now);

        let (user_id, entry) = codes
            .iter()
            .find(|(_, v)| v.code == code)
            .map(|(u, v)| (*u, v.clone()))
            .ok_or_else(|| ApiError::client_error("Invalid or expired link code.".to_string()))?;

        if entry.target_principal != *caller {
            return Err(ApiError::client_error(
                "Invalid or expired link code.".to_string(),
            ));
        }

        codes.remove(&user_id);
        Ok::<_, ApiError>(user_id)
    })?;

    user_profile_repository::link_principal_to_user(user_id, *caller)
}

pub fn unlink_my_principal(caller: &Principal, principal: Principal) -> ApiResult {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    user_profile_repository::unlink_principal_from_user(user_id, principal)
}

pub fn list_my_linked_principals(caller: &Principal) -> ApiResult<Vec<LinkedPrincipal>> {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    Ok(user_profile_repository::get_principals_with_names_by_user_id(user_id))
}

/// Set or clear the display name for one of the caller's linked principals.
/// Any of the user's principals may rename any other principal of the same
/// account; ownership is checked at the repository layer.
pub fn set_my_principal_name(
    caller: &Principal,
    principal: Principal,
    name: Option<String>,
) -> ApiResult {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    let validated = validate_optional_principal_name(name)?;
    user_profile_repository::set_principal_name(user_id, principal, validated)
}

#[derive(Debug, Clone)]
pub struct PendingLinkCodeEntry {
    pub code: String,
    pub expires_at_nanos: u64,
    pub target_principal: Principal,
}

pub fn get_my_pending_link_code(caller: &Principal) -> ApiResult<Option<PendingLinkCodeEntry>> {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    let now = now_nanos();

    PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        codes.retain(|_, v| v.expires_at_nanos > now);

        Ok(codes.get(&user_id).map(|v| PendingLinkCodeEntry {
            code: v.code.clone(),
            expires_at_nanos: v.expires_at_nanos,
            target_principal: v.target_principal,
        }))
    })
}

pub fn revoke_my_link_code(caller: &Principal) -> ApiResult {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;

    PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        if codes.remove(&user_id).is_none() {
            return Err(ApiError::client_error("Link code not found.".to_string()));
        }
        Ok(())
    })
}

// Staff-side: attach a principal to an existing user account without going
// through the device-to-device link-code dance. The escape hatch for users
// who have lost access to every principal currently on their account, and
// also the recovery path before email-based recovery exists.
//
// Caller must hold `MANAGE_USERS`. The target user_id must already exist;
// the target principal must be authenticated (anonymous is rejected) and
// must not be claimed by any other user — that constraint is enforced by
// the repository, matching the behavior of `link_my_principal`. There is
// no proof-of-control over `principal` here: the trust comes from the
// staff role.
pub fn admin_link_principal_to_user(
    caller: &Principal,
    user_id: Uuid,
    principal: Principal,
) -> ApiResult {
    access_control_service::assert_staff_perm(caller, StaffPermissions::MANAGE_USERS)?;

    if principal == Principal::anonymous() {
        return Err(ApiError::client_error(
            "Target principal must not be anonymous.".to_string(),
        ));
    }

    user_profile_repository::link_principal_to_user(user_id, principal)
}

// Staff-side: detach a principal from a user account. Mirrors
// `unlink_my_principal` and inherits the repository's "refuse to remove the
// user's last principal" guard so a staff action cannot orphan an account.
pub fn admin_unlink_principal_from_user(
    caller: &Principal,
    user_id: Uuid,
    principal: Principal,
) -> ApiResult {
    access_control_service::assert_staff_perm(caller, StaffPermissions::MANAGE_USERS)?;
    user_profile_repository::unlink_principal_from_user(user_id, principal)
}

// Staff-side: list the principals linked to a target user. The user-facing
// `list_my_linked_principals` is self-scoped; this version is for admin UI
// that needs to render and act on another user's principals.
pub fn admin_list_linked_principals(
    caller: &Principal,
    user_id: Uuid,
) -> ApiResult<Vec<Principal>> {
    access_control_service::assert_staff_perm(caller, StaffPermissions::MANAGE_USERS)?;
    Ok(user_profile_repository::get_principals_by_user_id(user_id))
}

fn validate_code_format(code: &str) -> ApiResult {
    if code.len() != LINK_CODE_LEN {
        return Err(ApiError::client_error(
            "Link code must be 8 characters.".to_string(),
        ));
    }
    if !code
        .chars()
        .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit())
    {
        return Err(ApiError::client_error(
            "Link code must use uppercase letters and digits only.".to_string(),
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::data::user_profile_repository::create_user_profile;
    use crate::data::{UserProfile, UserStatus};
    use canister_utils::Uuid;

    fn principal(byte: u8) -> Principal {
        let mut bytes = [0u8; 29];
        bytes[28] = byte;
        Principal::from_slice(&bytes)
    }

    fn fresh_user(byte: u8) -> Principal {
        let p = principal(byte);
        create_user_profile(p, UserProfile::default());
        p
    }

    // Active user with the given staff permissions. Returns (principal, user_id)
    // so tests can use the principal for caller-side checks and the user_id as
    // the admin-call target.
    fn fresh_staff_user(byte: u8, perms: StaffPermissions) -> (Principal, Uuid) {
        let p = principal(byte);
        let user_id = create_user_profile(
            p,
            UserProfile {
                status: UserStatus::Active,
                staff_permissions: Some(perms),
                ..UserProfile::default()
            },
        );
        (p, user_id)
    }

    fn user_id_of(p: Principal) -> Uuid {
        user_profile_repository::assert_user_id_by_principal(&p).unwrap()
    }

    #[test]
    fn validate_code_format_accepts_8_uppercase_alnum() {
        assert!(validate_code_format("ABC123XY").is_ok());
        assert!(validate_code_format("00000000").is_ok());
    }

    #[test]
    fn validate_code_format_rejects_wrong_length() {
        assert!(validate_code_format("").is_err());
        assert!(validate_code_format("ABC123X").is_err());
        assert!(validate_code_format("ABC123XYZ").is_err());
    }

    #[test]
    fn validate_code_format_rejects_lowercase_or_punctuation() {
        assert!(validate_code_format("abc123xy").is_err());
        assert!(validate_code_format("ABC-123X").is_err());
        assert!(validate_code_format("ABC 123X").is_err());
    }

    #[test]
    fn link_my_principal_rejects_unknown_code() {
        let p = principal(200);
        let err = link_my_principal(&p, "NOTACODE".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");
    }

    #[test]
    fn register_link_code_returns_expiry_at_ttl() {
        let owner = fresh_user(10);
        let target = principal(110);
        let out = register_link_code(&owner, "REGEXPRY".to_string(), target).unwrap();
        assert_eq!(out.expires_at_nanos, LINK_CODE_TTL_NANOS);
    }

    #[test]
    fn register_link_code_rejects_invalid_format() {
        let owner = fresh_user(11);
        let target = principal(111);
        let err = register_link_code(&owner, "lowercas".to_string(), target).unwrap_err();
        assert!(err.message().contains("uppercase"));
    }

    #[test]
    fn register_link_code_rejects_unknown_caller() {
        let stranger = principal(12);
        let target = principal(112);
        let err = register_link_code(&stranger, "STRANGER".to_string(), target).unwrap_err();
        assert!(!err.message().is_empty());
    }

    #[test]
    fn register_link_code_rejects_anonymous_target() {
        let owner = fresh_user(16);
        let err =
            register_link_code(&owner, "ANONTGT1".to_string(), Principal::anonymous()).unwrap_err();
        assert!(err.message().contains("anonymous"));
    }

    #[test]
    fn register_link_code_replaces_existing_pending_code() {
        let owner = fresh_user(13);
        let target = principal(113);
        register_link_code(&owner, "FIRSTOWN".to_string(), target).unwrap();
        register_link_code(&owner, "SECONDOW".to_string(), target).unwrap();

        let pending = get_my_pending_link_code(&owner).unwrap().unwrap();
        assert_eq!(pending.code, "SECONDOW");

        let err = link_my_principal(&target, "FIRSTOWN".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");
    }

    #[test]
    fn link_my_principal_attaches_new_principal_and_consumes_code() {
        let owner = fresh_user(20);
        let new_p = principal(21);
        register_link_code(&owner, "LINKOK01".to_string(), new_p).unwrap();

        link_my_principal(&new_p, "LINKOK01".to_string()).unwrap();

        let listed = list_my_linked_principals(&owner).unwrap();
        assert!(listed.iter().any(|e| e.principal == new_p));

        let err = link_my_principal(&new_p, "LINKOK01".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");
    }

    #[test]
    fn link_my_principal_rejects_caller_other_than_target_without_burning_code() {
        let owner = fresh_user(22);
        let target = principal(23);
        let attacker = principal(24);
        register_link_code(&owner, "BINDONLY".to_string(), target).unwrap();

        let err = link_my_principal(&attacker, "BINDONLY".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");

        // Mismatched attempts must not burn the code, otherwise an intercepting
        // party could deny the legitimate caller by racing first.
        link_my_principal(&target, "BINDONLY".to_string()).unwrap();
        let listed = list_my_linked_principals(&owner).unwrap();
        assert!(listed.iter().any(|e| e.principal == target));
        assert!(!listed.iter().any(|e| e.principal == attacker));
    }

    #[test]
    fn get_my_pending_link_code_returns_only_callers_code() {
        let owner = fresh_user(40);
        let other = fresh_user(41);
        let target_owner = principal(140);
        let target_other = principal(141);
        register_link_code(&owner, "MINECODE".to_string(), target_owner).unwrap();
        register_link_code(&other, "THEIRSAA".to_string(), target_other).unwrap();

        let mine = get_my_pending_link_code(&owner).unwrap().unwrap();
        assert_eq!(mine.code, "MINECODE");
        assert_eq!(mine.target_principal, target_owner);
    }

    #[test]
    fn revoke_my_link_code_removes_pending_code() {
        let owner = fresh_user(50);
        let target = principal(150);
        register_link_code(&owner, "REVOKEME".to_string(), target).unwrap();

        revoke_my_link_code(&owner).unwrap();

        let err = link_my_principal(&target, "REVOKEME".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");
    }

    #[test]
    fn revoke_my_link_code_errors_when_caller_has_none() {
        let owner = fresh_user(60);
        let attacker = fresh_user(61);
        let target = principal(160);
        register_link_code(&owner, "OWNCODE1".to_string(), target).unwrap();

        let err = revoke_my_link_code(&attacker).unwrap_err();
        assert_eq!(err.message(), "Link code not found.");

        assert_eq!(
            get_my_pending_link_code(&owner).unwrap().unwrap().code,
            "OWNCODE1"
        );
    }

    #[test]
    fn unlink_my_principal_removes_from_list() {
        let owner = fresh_user(30);
        let extra = principal(31);
        register_link_code(&owner, "UNLINK01".to_string(), extra).unwrap();
        link_my_principal(&extra, "UNLINK01".to_string()).unwrap();

        unlink_my_principal(&owner, extra).unwrap();
        let listed = list_my_linked_principals(&owner).unwrap();
        assert!(!listed.iter().any(|e| e.principal == extra));
        assert!(listed.iter().any(|e| e.principal == owner));
    }

    #[test]
    fn set_my_principal_name_persists_via_listing() {
        let owner = fresh_user(70);
        let extra = principal(71);
        register_link_code(&owner, "NAMEABLE".to_string(), extra).unwrap();
        link_my_principal(&extra, "NAMEABLE".to_string()).unwrap();

        set_my_principal_name(&owner, extra, Some("  Hardware wallet  ".to_string())).unwrap();

        let listed = list_my_linked_principals(&owner).unwrap();
        let entry = listed.iter().find(|e| e.principal == extra).unwrap();
        assert_eq!(entry.name.as_deref(), Some("Hardware wallet"));
    }

    #[test]
    fn set_my_principal_name_lets_sibling_principal_rename() {
        // P1 (caller `owner`) sets a name for P2 (`extra`), then P2 sets a
        // name for P1. Both must succeed because authorization is by user
        // account, not by which specific principal is making the call.
        let owner = fresh_user(80);
        let extra = principal(81);
        register_link_code(&owner, "SIBLINGS".to_string(), extra).unwrap();
        link_my_principal(&extra, "SIBLINGS".to_string()).unwrap();

        set_my_principal_name(&owner, extra, Some("Phone".to_string())).unwrap();
        set_my_principal_name(&extra, owner, Some("Laptop".to_string())).unwrap();

        let listed = list_my_linked_principals(&owner).unwrap();
        let owner_entry = listed.iter().find(|e| e.principal == owner).unwrap();
        let extra_entry = listed.iter().find(|e| e.principal == extra).unwrap();
        assert_eq!(owner_entry.name.as_deref(), Some("Laptop"));
        assert_eq!(extra_entry.name.as_deref(), Some("Phone"));
    }

    #[test]
    fn set_my_principal_name_rejects_principal_owned_by_other_account() {
        let owner = fresh_user(90);
        let stranger = fresh_user(91);

        let err = set_my_principal_name(&owner, stranger, Some("Mine!".to_string())).unwrap_err();
        assert_eq!(err.message(), "Principal cannot be renamed.");
    }

    #[test]
    fn set_my_principal_name_with_empty_string_clears() {
        let owner = fresh_user(100);
        let extra = principal(101);
        register_link_code(&owner, "CLEAR001".to_string(), extra).unwrap();
        link_my_principal(&extra, "CLEAR001".to_string()).unwrap();
        set_my_principal_name(&owner, extra, Some("Old".to_string())).unwrap();

        set_my_principal_name(&owner, extra, Some("   ".to_string())).unwrap();

        let listed = list_my_linked_principals(&owner).unwrap();
        let entry = listed.iter().find(|e| e.principal == extra).unwrap();
        assert_eq!(entry.name, None);
    }

    #[test]
    fn set_my_principal_name_rejects_oversized_name() {
        let owner = fresh_user(110);
        let extra = principal(111);
        register_link_code(&owner, "TOOLONG1".to_string(), extra).unwrap();
        link_my_principal(&extra, "TOOLONG1".to_string()).unwrap();

        let oversized = "a".repeat(65);
        let err = set_my_principal_name(&owner, extra, Some(oversized)).unwrap_err();
        assert!(err.message().contains("64 characters"));
    }

    #[test]
    fn admin_link_principal_attaches_to_target_user() {
        let (staff, _) = fresh_staff_user(70, StaffPermissions::MANAGE_USERS);
        let target_owner = fresh_user(71);
        let target_user_id = user_id_of(target_owner);
        let new_principal = principal(72);

        admin_link_principal_to_user(&staff, target_user_id, new_principal).unwrap();

        let principals = user_profile_repository::get_principals_by_user_id(target_user_id);
        assert!(principals.contains(&new_principal));
    }

    #[test]
    fn admin_link_principal_rejects_caller_without_manage_users() {
        // Has WRITE_BILLING but not MANAGE_USERS — the permission gate must
        // discriminate flag-by-flag, not just "is staff at all".
        let (staff, _) = fresh_staff_user(73, StaffPermissions::WRITE_BILLING);
        let target_owner = fresh_user(74);
        let target_user_id = user_id_of(target_owner);
        let new_principal = principal(75);

        let err = admin_link_principal_to_user(&staff, target_user_id, new_principal).unwrap_err();
        assert!(err.message().contains("staff permissions"));

        let principals = user_profile_repository::get_principals_by_user_id(target_user_id);
        assert!(!principals.contains(&new_principal));
    }

    #[test]
    fn admin_link_principal_rejects_non_staff_caller() {
        let stranger = fresh_user(76);
        let target_owner = fresh_user(77);
        let target_user_id = user_id_of(target_owner);
        let new_principal = principal(78);

        let err =
            admin_link_principal_to_user(&stranger, target_user_id, new_principal).unwrap_err();
        assert!(!err.message().is_empty());

        let principals = user_profile_repository::get_principals_by_user_id(target_user_id);
        assert!(!principals.contains(&new_principal));
    }

    #[test]
    fn admin_link_principal_rejects_anonymous_target() {
        let (staff, _) = fresh_staff_user(79, StaffPermissions::MANAGE_USERS);
        let target_owner = fresh_user(80);
        let target_user_id = user_id_of(target_owner);

        let err = admin_link_principal_to_user(&staff, target_user_id, Principal::anonymous())
            .unwrap_err();
        assert!(err.message().contains("anonymous"));
    }

    #[test]
    fn admin_link_principal_rejects_already_claimed_principal() {
        // Repository-level guard surfaces through the admin path: an admin
        // cannot silently steal a principal already linked to a different
        // user.
        let (staff, _) = fresh_staff_user(81, StaffPermissions::MANAGE_USERS);
        let other_owner = fresh_user(82);
        let target_owner = fresh_user(83);
        let target_user_id = user_id_of(target_owner);

        let err = admin_link_principal_to_user(&staff, target_user_id, other_owner).unwrap_err();
        assert_eq!(err.message(), "Principal cannot be linked.");
    }

    #[test]
    fn admin_unlink_principal_removes_link() {
        let (staff, _) = fresh_staff_user(84, StaffPermissions::MANAGE_USERS);
        let target_owner = fresh_user(85);
        let target_user_id = user_id_of(target_owner);
        let extra = principal(86);
        user_profile_repository::link_principal_to_user(target_user_id, extra).unwrap();

        admin_unlink_principal_from_user(&staff, target_user_id, extra).unwrap();

        let principals = user_profile_repository::get_principals_by_user_id(target_user_id);
        assert!(!principals.contains(&extra));
        assert!(principals.contains(&target_owner));
    }

    #[test]
    fn admin_unlink_principal_refuses_last_principal() {
        // The repository's "do not orphan an account" guard must apply to
        // staff actions too; a staff member with MANAGE_USERS can still not
        // remove a user's only remaining principal.
        let (staff, _) = fresh_staff_user(87, StaffPermissions::MANAGE_USERS);
        let target_owner = fresh_user(88);
        let target_user_id = user_id_of(target_owner);

        let err =
            admin_unlink_principal_from_user(&staff, target_user_id, target_owner).unwrap_err();
        assert_eq!(err.message(), "Principal cannot be unlinked.");
    }

    #[test]
    fn admin_unlink_principal_rejects_caller_without_manage_users() {
        let (staff, _) = fresh_staff_user(89, StaffPermissions::READ_ALL_ORGS);
        let target_owner = fresh_user(90);
        let target_user_id = user_id_of(target_owner);
        let extra = principal(91);
        user_profile_repository::link_principal_to_user(target_user_id, extra).unwrap();

        let err = admin_unlink_principal_from_user(&staff, target_user_id, extra).unwrap_err();
        assert!(err.message().contains("staff permissions"));

        let principals = user_profile_repository::get_principals_by_user_id(target_user_id);
        assert!(principals.contains(&extra));
    }
}
