// Pending link codes are kept in heap, not stable memory: they are single-use
// bearer tokens, and losing them on canister upgrade just means the user
// generates a new one. Not worth the stable-memory ceremony.
//
// Codes are generated by the frontend, not the backend: a backend RNG would
// require an inter-canister call to `raw_rand` (only available in update
// calls, async, and overkill for a single-use token). The browser's
// `crypto.getRandomValues` is just as good for an unguessable bearer token,
// and the backend still owns the binding (`code -> user_id`) and the
// single-use guarantee at consume time. Standard OAuth-`state` pattern.

use crate::data::user_profile_repository;
use candid::Principal;
use canister_utils::{now_nanos, ApiError, ApiResult, Uuid};
use std::cell::RefCell;
use std::collections::HashMap;

// 15 minutes is long enough to switch identities and run a `dfx canister call`,
// short enough that abandoned codes evict on their own without needing a sweep.
const LINK_CODE_TTL_NANOS: u64 = 15 * 60 * 1_000_000_000;
const MAX_PENDING_CODES_PER_USER: usize = 5;
const LINK_CODE_LEN: usize = 8;

thread_local! {
    static PENDING_LINK_CODES: RefCell<HashMap<String, PendingLinkCode>> = RefCell::new(HashMap::new());
}

#[derive(Clone)]
struct PendingLinkCode {
    user_id: Uuid,
    expires_at_nanos: u64,
}

#[derive(Debug)]
pub struct RegisteredLinkCode {
    pub expires_at_nanos: u64,
}

pub fn register_link_code(caller: &Principal, code: String) -> ApiResult<RegisteredLinkCode> {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    validate_code_format(&code)?;

    let now = now_nanos();
    let expires_at = now.saturating_add(LINK_CODE_TTL_NANOS);

    PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        codes.retain(|_, v| v.expires_at_nanos > now);

        let owned_count = codes.values().filter(|v| v.user_id == user_id).count();
        if owned_count >= MAX_PENDING_CODES_PER_USER {
            return Err(ApiError::client_error(
                "Too many pending link codes; consume or replace one before generating another."
                    .to_string(),
            ));
        }

        if codes.contains_key(&code) {
            return Err(ApiError::client_error("Link code unavailable.".to_string()));
        }

        codes.insert(
            code,
            PendingLinkCode {
                user_id,
                expires_at_nanos: expires_at,
            },
        );
        Ok(RegisteredLinkCode {
            expires_at_nanos: expires_at,
        })
    })
}

pub fn link_my_principal(caller: &Principal, code: String) -> ApiResult {
    let now = now_nanos();

    let user_id = PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        codes.retain(|_, v| v.expires_at_nanos > now);

        let entry = codes
            .remove(&code)
            .ok_or_else(|| ApiError::client_error("Invalid or expired link code.".to_string()))?;
        Ok::<_, ApiError>(entry.user_id)
    })?;

    user_profile_repository::link_principal_to_user(user_id, *caller)
}

pub fn unlink_my_principal(caller: &Principal, principal: Principal) -> ApiResult {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    user_profile_repository::unlink_principal_from_user(user_id, principal)
}

pub fn list_my_linked_principals(caller: &Principal) -> ApiResult<Vec<Principal>> {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    Ok(user_profile_repository::get_principals_by_user_id(user_id))
}

#[derive(Debug, Clone)]
pub struct PendingLinkCodeEntry {
    pub code: String,
    pub expires_at_nanos: u64,
}

pub fn list_my_pending_link_codes(caller: &Principal) -> ApiResult<Vec<PendingLinkCodeEntry>> {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    let now = now_nanos();

    PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        codes.retain(|_, v| v.expires_at_nanos > now);

        let mut out: Vec<PendingLinkCodeEntry> = codes
            .iter()
            .filter(|(_, v)| v.user_id == user_id)
            .map(|(code, v)| PendingLinkCodeEntry {
                code: code.clone(),
                expires_at_nanos: v.expires_at_nanos,
            })
            .collect();
        out.sort_by_key(|e| e.expires_at_nanos);
        Ok(out)
    })
}

pub fn revoke_link_code(caller: &Principal, code: String) -> ApiResult {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;

    PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        match codes.get(&code) {
            Some(entry) if entry.user_id == user_id => {
                codes.remove(&code);
                Ok(())
            }
            // Don't leak whether the code exists for someone else.
            _ => Err(ApiError::client_error("Link code not found.".to_string())),
        }
    })
}

fn validate_code_format(code: &str) -> ApiResult {
    if code.len() != LINK_CODE_LEN {
        return Err(ApiError::client_error(
            "Link code must be 8 characters.".to_string(),
        ));
    }
    if !code
        .chars()
        .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit())
    {
        return Err(ApiError::client_error(
            "Link code must use uppercase letters and digits only.".to_string(),
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::data::user_profile_repository::create_user_profile;
    use crate::data::UserProfile;

    fn principal(byte: u8) -> Principal {
        let mut bytes = [0u8; 29];
        bytes[28] = byte;
        Principal::from_slice(&bytes)
    }

    fn fresh_user(byte: u8) -> Principal {
        let p = principal(byte);
        create_user_profile(p, UserProfile::default());
        p
    }

    #[test]
    fn validate_code_format_accepts_8_uppercase_alnum() {
        assert!(validate_code_format("ABC123XY").is_ok());
        assert!(validate_code_format("00000000").is_ok());
    }

    #[test]
    fn validate_code_format_rejects_wrong_length() {
        assert!(validate_code_format("").is_err());
        assert!(validate_code_format("ABC123X").is_err());
        assert!(validate_code_format("ABC123XYZ").is_err());
    }

    #[test]
    fn validate_code_format_rejects_lowercase_or_punctuation() {
        assert!(validate_code_format("abc123xy").is_err());
        assert!(validate_code_format("ABC-123X").is_err());
        assert!(validate_code_format("ABC 123X").is_err());
    }

    #[test]
    fn link_my_principal_rejects_unknown_code() {
        let p = principal(200);
        let err = link_my_principal(&p, "NOTACODE".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");
    }

    #[test]
    fn register_link_code_returns_expiry_at_ttl() {
        // now_nanos() is 0 outside wasm, so expiry equals the TTL itself.
        let owner = fresh_user(10);
        let out = register_link_code(&owner, "REGEXPRY".to_string()).unwrap();
        assert_eq!(out.expires_at_nanos, LINK_CODE_TTL_NANOS);
    }

    #[test]
    fn register_link_code_rejects_invalid_format() {
        let owner = fresh_user(11);
        let err = register_link_code(&owner, "lowercas".to_string()).unwrap_err();
        assert!(err.message().contains("uppercase"));
    }

    #[test]
    fn register_link_code_rejects_unknown_caller() {
        let stranger = principal(12);
        let err = register_link_code(&stranger, "STRANGER".to_string()).unwrap_err();
        // Surfaces whatever assert_user_id_by_principal returns for unknown
        // principals; we just want a failure, not a specific message.
        assert!(!err.message().is_empty());
    }

    #[test]
    fn register_link_code_rejects_collision() {
        let a = fresh_user(13);
        let b = fresh_user(14);
        register_link_code(&a, "COLLIDE1".to_string()).unwrap();
        let err = register_link_code(&b, "COLLIDE1".to_string()).unwrap_err();
        assert_eq!(err.message(), "Link code unavailable.");
    }

    #[test]
    fn register_link_code_caps_pending_per_user() {
        let owner = fresh_user(15);
        let codes = ["CAPCODE1", "CAPCODE2", "CAPCODE3", "CAPCODE4", "CAPCODE5"];
        for c in codes {
            register_link_code(&owner, c.to_string()).unwrap();
        }
        let err = register_link_code(&owner, "CAPCODE6".to_string()).unwrap_err();
        assert!(err.message().contains("Too many pending link codes"));
    }

    #[test]
    fn link_my_principal_attaches_new_principal_and_consumes_code() {
        let owner = fresh_user(20);
        let new_p = principal(21);
        register_link_code(&owner, "LINKOK01".to_string()).unwrap();

        link_my_principal(&new_p, "LINKOK01".to_string()).unwrap();

        let listed = list_my_linked_principals(&owner).unwrap();
        assert!(listed.contains(&new_p));

        // Code is single-use.
        let err = link_my_principal(&new_p, "LINKOK01".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");
    }

    #[test]
    fn list_my_pending_link_codes_returns_only_callers_codes() {
        let owner = fresh_user(40);
        let other = fresh_user(41);
        register_link_code(&owner, "MINEAAAA".to_string()).unwrap();
        register_link_code(&owner, "MINEBBBB".to_string()).unwrap();
        register_link_code(&other, "THEIRSAA".to_string()).unwrap();

        let mine = list_my_pending_link_codes(&owner).unwrap();
        let codes: Vec<&str> = mine.iter().map(|e| e.code.as_str()).collect();
        assert!(codes.contains(&"MINEAAAA"));
        assert!(codes.contains(&"MINEBBBB"));
        assert!(!codes.contains(&"THEIRSAA"));
    }

    #[test]
    fn revoke_link_code_removes_pending_code() {
        let owner = fresh_user(50);
        register_link_code(&owner, "REVOKEME".to_string()).unwrap();

        revoke_link_code(&owner, "REVOKEME".to_string()).unwrap();

        let stranger = principal(51);
        let err = link_my_principal(&stranger, "REVOKEME".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");
    }

    #[test]
    fn revoke_link_code_rejects_other_users_code() {
        let owner = fresh_user(60);
        let attacker = fresh_user(61);
        register_link_code(&owner, "OWNCODE1".to_string()).unwrap();

        let err = revoke_link_code(&attacker, "OWNCODE1".to_string()).unwrap_err();
        assert_eq!(err.message(), "Link code not found.");

        // Owner's code is still usable.
        assert!(list_my_pending_link_codes(&owner)
            .unwrap()
            .iter()
            .any(|e| e.code == "OWNCODE1"));
    }

    #[test]
    fn unlink_my_principal_removes_from_list() {
        let owner = fresh_user(30);
        let extra = principal(31);
        register_link_code(&owner, "UNLINK01".to_string()).unwrap();
        link_my_principal(&extra, "UNLINK01".to_string()).unwrap();

        unlink_my_principal(&owner, extra).unwrap();
        let listed = list_my_linked_principals(&owner).unwrap();
        assert!(!listed.contains(&extra));
        assert!(listed.contains(&owner));
    }
}
