// Pending link codes live in heap, not stable memory: single-use bearer
// tokens, losing them on upgrade just means the user generates a new one.
//
// Codes are generated by the frontend (browser CSPRNG). The backend owns
// the binding and the single-use guarantee. Standard OAuth-`state` pattern.
//
// At most one pending code per user; registering replaces any existing one.

use crate::data::user_profile_repository;
use candid::Principal;
use canister_utils::{now_nanos, ApiError, ApiResult, Uuid};
use std::cell::RefCell;
use std::collections::HashMap;

const LINK_CODE_TTL_NANOS: u64 = 15 * 60 * 1_000_000_000;
const LINK_CODE_LEN: usize = 8;

thread_local! {
    static PENDING_LINK_CODES: RefCell<HashMap<Uuid, PendingLinkCode>> = RefCell::new(HashMap::new());
}

#[derive(Clone)]
struct PendingLinkCode {
    code: String,
    target_principal: Principal,
    expires_at_nanos: u64,
}

#[derive(Debug)]
pub struct RegisteredLinkCode {
    pub expires_at_nanos: u64,
}

pub fn register_link_code(
    caller: &Principal,
    code: String,
    target_principal: Principal,
) -> ApiResult<RegisteredLinkCode> {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    validate_code_format(&code)?;

    if target_principal == Principal::anonymous() {
        return Err(ApiError::client_error(
            "Target principal must not be anonymous.".to_string(),
        ));
    }

    let now = now_nanos();
    let expires_at = now.saturating_add(LINK_CODE_TTL_NANOS);

    PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        codes.retain(|_, v| v.expires_at_nanos > now);
        codes.insert(
            user_id,
            PendingLinkCode {
                code,
                target_principal,
                expires_at_nanos: expires_at,
            },
        );
    });

    Ok(RegisteredLinkCode {
        expires_at_nanos: expires_at,
    })
}

pub fn link_my_principal(caller: &Principal, code: String) -> ApiResult {
    let now = now_nanos();

    let user_id = PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        codes.retain(|_, v| v.expires_at_nanos > now);

        let (user_id, entry) = codes
            .iter()
            .find(|(_, v)| v.code == code)
            .map(|(u, v)| (*u, v.clone()))
            .ok_or_else(|| ApiError::client_error("Invalid or expired link code.".to_string()))?;

        if entry.target_principal != *caller {
            return Err(ApiError::client_error(
                "Invalid or expired link code.".to_string(),
            ));
        }

        codes.remove(&user_id);
        Ok::<_, ApiError>(user_id)
    })?;

    user_profile_repository::link_principal_to_user(user_id, *caller)
}

pub fn unlink_my_principal(caller: &Principal, principal: Principal) -> ApiResult {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    user_profile_repository::unlink_principal_from_user(user_id, principal)
}

pub fn list_my_linked_principals(caller: &Principal) -> ApiResult<Vec<Principal>> {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    Ok(user_profile_repository::get_principals_by_user_id(user_id))
}

#[derive(Debug, Clone)]
pub struct PendingLinkCodeEntry {
    pub code: String,
    pub expires_at_nanos: u64,
    pub target_principal: Principal,
}

pub fn get_my_pending_link_code(caller: &Principal) -> ApiResult<Option<PendingLinkCodeEntry>> {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;
    let now = now_nanos();

    PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        codes.retain(|_, v| v.expires_at_nanos > now);

        Ok(codes.get(&user_id).map(|v| PendingLinkCodeEntry {
            code: v.code.clone(),
            expires_at_nanos: v.expires_at_nanos,
            target_principal: v.target_principal,
        }))
    })
}

pub fn revoke_my_link_code(caller: &Principal) -> ApiResult {
    let user_id = user_profile_repository::assert_user_id_by_principal(caller)?;

    PENDING_LINK_CODES.with(|cell| {
        let mut codes = cell.borrow_mut();
        if codes.remove(&user_id).is_none() {
            return Err(ApiError::client_error("Link code not found.".to_string()));
        }
        Ok(())
    })
}

fn validate_code_format(code: &str) -> ApiResult {
    if code.len() != LINK_CODE_LEN {
        return Err(ApiError::client_error(
            "Link code must be 8 characters.".to_string(),
        ));
    }
    if !code
        .chars()
        .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit())
    {
        return Err(ApiError::client_error(
            "Link code must use uppercase letters and digits only.".to_string(),
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::data::user_profile_repository::create_user_profile;
    use crate::data::UserProfile;

    fn principal(byte: u8) -> Principal {
        let mut bytes = [0u8; 29];
        bytes[28] = byte;
        Principal::from_slice(&bytes)
    }

    fn fresh_user(byte: u8) -> Principal {
        let p = principal(byte);
        create_user_profile(p, UserProfile::default());
        p
    }

    #[test]
    fn validate_code_format_accepts_8_uppercase_alnum() {
        assert!(validate_code_format("ABC123XY").is_ok());
        assert!(validate_code_format("00000000").is_ok());
    }

    #[test]
    fn validate_code_format_rejects_wrong_length() {
        assert!(validate_code_format("").is_err());
        assert!(validate_code_format("ABC123X").is_err());
        assert!(validate_code_format("ABC123XYZ").is_err());
    }

    #[test]
    fn validate_code_format_rejects_lowercase_or_punctuation() {
        assert!(validate_code_format("abc123xy").is_err());
        assert!(validate_code_format("ABC-123X").is_err());
        assert!(validate_code_format("ABC 123X").is_err());
    }

    #[test]
    fn link_my_principal_rejects_unknown_code() {
        let p = principal(200);
        let err = link_my_principal(&p, "NOTACODE".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");
    }

    #[test]
    fn register_link_code_returns_expiry_at_ttl() {
        let owner = fresh_user(10);
        let target = principal(110);
        let out = register_link_code(&owner, "REGEXPRY".to_string(), target).unwrap();
        assert_eq!(out.expires_at_nanos, LINK_CODE_TTL_NANOS);
    }

    #[test]
    fn register_link_code_rejects_invalid_format() {
        let owner = fresh_user(11);
        let target = principal(111);
        let err = register_link_code(&owner, "lowercas".to_string(), target).unwrap_err();
        assert!(err.message().contains("uppercase"));
    }

    #[test]
    fn register_link_code_rejects_unknown_caller() {
        let stranger = principal(12);
        let target = principal(112);
        let err = register_link_code(&stranger, "STRANGER".to_string(), target).unwrap_err();
        assert!(!err.message().is_empty());
    }

    #[test]
    fn register_link_code_rejects_anonymous_target() {
        let owner = fresh_user(16);
        let err =
            register_link_code(&owner, "ANONTGT1".to_string(), Principal::anonymous()).unwrap_err();
        assert!(err.message().contains("anonymous"));
    }

    #[test]
    fn register_link_code_replaces_existing_pending_code() {
        let owner = fresh_user(13);
        let target = principal(113);
        register_link_code(&owner, "FIRSTOWN".to_string(), target).unwrap();
        register_link_code(&owner, "SECONDOW".to_string(), target).unwrap();

        let pending = get_my_pending_link_code(&owner).unwrap().unwrap();
        assert_eq!(pending.code, "SECONDOW");

        let err = link_my_principal(&target, "FIRSTOWN".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");
    }

    #[test]
    fn link_my_principal_attaches_new_principal_and_consumes_code() {
        let owner = fresh_user(20);
        let new_p = principal(21);
        register_link_code(&owner, "LINKOK01".to_string(), new_p).unwrap();

        link_my_principal(&new_p, "LINKOK01".to_string()).unwrap();

        let listed = list_my_linked_principals(&owner).unwrap();
        assert!(listed.contains(&new_p));

        let err = link_my_principal(&new_p, "LINKOK01".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");
    }

    #[test]
    fn link_my_principal_rejects_caller_other_than_target_without_burning_code() {
        let owner = fresh_user(22);
        let target = principal(23);
        let attacker = principal(24);
        register_link_code(&owner, "BINDONLY".to_string(), target).unwrap();

        let err = link_my_principal(&attacker, "BINDONLY".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");

        // Mismatched attempts must not burn the code, otherwise an intercepting
        // party could deny the legitimate caller by racing first.
        link_my_principal(&target, "BINDONLY".to_string()).unwrap();
        let listed = list_my_linked_principals(&owner).unwrap();
        assert!(listed.contains(&target));
        assert!(!listed.contains(&attacker));
    }

    #[test]
    fn get_my_pending_link_code_returns_only_callers_code() {
        let owner = fresh_user(40);
        let other = fresh_user(41);
        let target_owner = principal(140);
        let target_other = principal(141);
        register_link_code(&owner, "MINECODE".to_string(), target_owner).unwrap();
        register_link_code(&other, "THEIRSAA".to_string(), target_other).unwrap();

        let mine = get_my_pending_link_code(&owner).unwrap().unwrap();
        assert_eq!(mine.code, "MINECODE");
        assert_eq!(mine.target_principal, target_owner);
    }

    #[test]
    fn revoke_my_link_code_removes_pending_code() {
        let owner = fresh_user(50);
        let target = principal(150);
        register_link_code(&owner, "REVOKEME".to_string(), target).unwrap();

        revoke_my_link_code(&owner).unwrap();

        let err = link_my_principal(&target, "REVOKEME".to_string()).unwrap_err();
        assert_eq!(err.message(), "Invalid or expired link code.");
    }

    #[test]
    fn revoke_my_link_code_errors_when_caller_has_none() {
        let owner = fresh_user(60);
        let attacker = fresh_user(61);
        let target = principal(160);
        register_link_code(&owner, "OWNCODE1".to_string(), target).unwrap();

        let err = revoke_my_link_code(&attacker).unwrap_err();
        assert_eq!(err.message(), "Link code not found.");

        assert_eq!(
            get_my_pending_link_code(&owner).unwrap().unwrap().code,
            "OWNCODE1"
        );
    }

    #[test]
    fn unlink_my_principal_removes_from_list() {
        let owner = fresh_user(30);
        let extra = principal(31);
        register_link_code(&owner, "UNLINK01".to_string(), extra).unwrap();
        link_my_principal(&extra, "UNLINK01".to_string()).unwrap();

        unlink_my_principal(&owner, extra).unwrap();
        let listed = list_my_linked_principals(&owner).unwrap();
        assert!(!listed.contains(&extra));
        assert!(listed.contains(&owner));
    }
}
