// Package backend provides a client for the "backend" canister.
// Do NOT edit this file. It was automatically generated by https://github.com/aviate-labs/agent-go.
package backend

import (
    "github.com/aviate-labs/agent-go"
    "github.com/aviate-labs/agent-go/candid/idl"
    "github.com/aviate-labs/agent-go/principal"
)

type CanisterUsage struct {
	CanisterId                     principal.Principal `ic:"canister_id" json:"canister_id"`
	Memory                         uint64              `ic:"memory" json:"memory"`
	MemoryBytes                    uint64              `ic:"memory_bytes" json:"memory_bytes"`
	ComputeAllocation              uint64              `ic:"compute_allocation" json:"compute_allocation"`
	ComputeAllocationPercent       uint64              `ic:"compute_allocation_percent" json:"compute_allocation_percent"`
	IngressInduction               uint64              `ic:"ingress_induction" json:"ingress_induction"`
	IngressInductionBytesTotal     uint64              `ic:"ingress_induction_bytes_total" json:"ingress_induction_bytes_total"`
	Instructions                   uint64              `ic:"instructions" json:"instructions"`
	ComputeTimeSecondsTotal        uint64              `ic:"compute_time_seconds_total" json:"compute_time_seconds_total"`
	RequestAndResponseTransmission uint64              `ic:"request_and_response_transmission" json:"request_and_response_transmission"`
	TransmissionBytesTotal         uint64              `ic:"transmission_bytes_total" json:"transmission_bytes_total"`
	Uninstall                      uint64              `ic:"uninstall" json:"uninstall"`
	UninstallsTotal                uint64              `ic:"uninstalls_total" json:"uninstalls_total"`
	HttpOutcalls                   uint64              `ic:"http_outcalls" json:"http_outcalls"`
	BurnedCycles                   uint64              `ic:"burned_cycles" json:"burned_cycles"`
}

type RecordUsageRequest struct {
	Usages []CanisterUsage `ic:"usages" json:"usages"`
}

type RecordUsageResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type ProjectUsage struct {
	Memory                         uint64 `ic:"memory" json:"memory"`
	MemoryBytes                    uint64 `ic:"memory_bytes" json:"memory_bytes"`
	ComputeAllocation              uint64 `ic:"compute_allocation" json:"compute_allocation"`
	ComputeAllocationPercent       uint64 `ic:"compute_allocation_percent" json:"compute_allocation_percent"`
	IngressInduction               uint64 `ic:"ingress_induction" json:"ingress_induction"`
	IngressInductionBytesTotal     uint64 `ic:"ingress_induction_bytes_total" json:"ingress_induction_bytes_total"`
	Instructions                   uint64 `ic:"instructions" json:"instructions"`
	ComputeTimeSecondsTotal        uint64 `ic:"compute_time_seconds_total" json:"compute_time_seconds_total"`
	RequestAndResponseTransmission uint64 `ic:"request_and_response_transmission" json:"request_and_response_transmission"`
	TransmissionBytesTotal         uint64 `ic:"transmission_bytes_total" json:"transmission_bytes_total"`
	Uninstall                      uint64 `ic:"uninstall" json:"uninstall"`
	UninstallsTotal                uint64 `ic:"uninstalls_total" json:"uninstalls_total"`
	HttpOutcalls                   uint64 `ic:"http_outcalls" json:"http_outcalls"`
	BurnedCycles                   uint64 `ic:"burned_cycles" json:"burned_cycles"`
}

type GetUsageRequest struct {
	ProjectId    ProjectId `ic:"project_id" json:"project_id"`
	BillingMonth *string   `ic:"billing_month,omitempty" json:"billing_month,omitempty"`
}

type GetUsageResponseData struct {
	Project   ProjectUsage    `ic:"project" json:"project"`
	Canisters []CanisterUsage `ic:"canisters" json:"canisters"`
}

type GetUsageResponse struct {
	Ok  *GetUsageResponseData `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError             `ic:"Err,variant" json:"Err,omitempty"`
}

type ListUserProfilesResponse struct {
	Ok  *[]UserProfile `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError      `ic:"Err,variant" json:"Err,omitempty"`
}

type GetUserProfilesByPrincipalsRequest struct {
	ProjectId  ProjectId             `ic:"project_id" json:"project_id"`
	Principals []principal.Principal `ic:"principals" json:"principals"`
}

type GetUserProfilesByPrincipalsResponse struct {
	Ok  *struct {
	Profiles []UserProfileByPrincipal `ic:"profiles" json:"profiles"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                           `ic:"Err,variant" json:"Err,omitempty"`
}

type UserProfileByPrincipal struct {
	SubjectPrincipal principal.Principal `ic:"subject_principal" json:"subject_principal"`
	Profile          *UserProfileBrief   `ic:"profile,omitempty" json:"profile,omitempty"`
}

type UserProfileBrief struct {
	Id            UserId  `ic:"id" json:"id"`
	Email         *string `ic:"email,omitempty" json:"email,omitempty"`
	EmailVerified bool    `ic:"email_verified" json:"email_verified"`
}

type GetUserProfilesByUserIdsRequest struct {
	ProjectId ProjectId `ic:"project_id" json:"project_id"`
	UserIds   []UserId  `ic:"user_ids" json:"user_ids"`
}

type GetUserProfilesByUserIdsResponse struct {
	Ok  *struct {
	Profiles []UserProfileBrief `ic:"profiles" json:"profiles"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                     `ic:"Err,variant" json:"Err,omitempty"`
}

type GetMyUserProfileResponse struct {
	Ok  **UserProfile `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError     `ic:"Err,variant" json:"Err,omitempty"`
}

type CreateMyUserProfileResponse struct {
	Ok  *UserProfile `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError    `ic:"Err,variant" json:"Err,omitempty"`
}

type UpdateMyUserProfileRequest struct {
	Email *string `ic:"email,omitempty" json:"email,omitempty"`
}

type UpdateMyUserProfileResponse struct {
	Ok  *idl.Null `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type UpdateUserProfileRequest struct {
	UserId UserId      `ic:"user_id" json:"user_id"`
	Status *UserStatus `ic:"status,omitempty" json:"status,omitempty"`
}

type UpdateUserProfileResponse struct {
	Ok  *idl.Null `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type UserProfile struct {
	Id            UserId     `ic:"id" json:"id"`
	Email         *string    `ic:"email,omitempty" json:"email,omitempty"`
	EmailVerified bool       `ic:"email_verified" json:"email_verified"`
	Status        UserStatus `ic:"status" json:"status"`
	IsAdmin       bool       `ic:"is_admin" json:"is_admin"`
}

type UserStatus struct {
	Active   *idl.Null `ic:"Active,variant" json:"Active,omitempty"`
	Inactive *idl.Null `ic:"Inactive,variant" json:"Inactive,omitempty"`
}

type GetUserStatsResponse struct {
	Ok  *struct {
	Total    uint64 `ic:"total" json:"total"`
	Active   uint64 `ic:"active" json:"active"`
	Inactive uint64 `ic:"inactive" json:"inactive"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                         `ic:"Err,variant" json:"Err,omitempty"`
}

type StaleUserEntry struct {
	Id    UserId  `ic:"id" json:"id"`
	Email *string `ic:"email,omitempty" json:"email,omitempty"`
}

type ListStaleUsersResponse struct {
	Ok  *[]StaleUserEntry `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError         `ic:"Err,variant" json:"Err,omitempty"`
}

type VerifyEmailRequest struct {
	Token string `ic:"token" json:"token"`
}

type VerifyEmailResponse struct {
	Ok  *idl.Null       `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *RejectionError `ic:"Err,variant" json:"Err,omitempty"`
}

type ListTrustedPartnersResponse struct {
	Ok  *[]TrustedPartner `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError         `ic:"Err,variant" json:"Err,omitempty"`
}

type CreateTrustedPartnerRequest struct {
	PrincipalId string `ic:"principal_id" json:"principal_id"`
	Name        string `ic:"name" json:"name"`
}

type CreateTrustedPartnerResponse struct {
	Ok  *TrustedPartner `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError       `ic:"Err,variant" json:"Err,omitempty"`
}

type TrustedPartner struct {
	Id          TrustedPartnerId `ic:"id" json:"id"`
	PrincipalId string           `ic:"principal_id" json:"principal_id"`
	Name        string           `ic:"name" json:"name"`
}

type GetLatestTermsAndConditionsResponse struct {
	Ok  **TermsAndConditions `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError            `ic:"Err,variant" json:"Err,omitempty"`
}

type ListTermsAndConditionsResponse struct {
	Ok  *[]TermsAndConditionsListItem `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                     `ic:"Err,variant" json:"Err,omitempty"`
}

type TermsAndConditions struct {
	Id          TermsAndConditionsId `ic:"id" json:"id"`
	Content     string               `ic:"content" json:"content"`
	Comment     string               `ic:"comment" json:"comment"`
	CreatedAt   uint64               `ic:"created_at" json:"created_at"`
	HasAccepted bool                 `ic:"has_accepted" json:"has_accepted"`
}

type TermsAndConditionsListItem struct {
	Id        TermsAndConditionsId `ic:"id" json:"id"`
	Content   string               `ic:"content" json:"content"`
	Comment   string               `ic:"comment" json:"comment"`
	CreatedAt uint64               `ic:"created_at" json:"created_at"`
	CreatedBy UserId               `ic:"created_by" json:"created_by"`
}

type CreateTermsAndConditionsRequest struct {
	Content string `ic:"content" json:"content"`
	Comment string `ic:"comment" json:"comment"`
}

type CreateTermsAndConditionsResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type UpsertTermsAndConditionsDecisionRequest struct {
	TermsAndConditionsId TermsAndConditionsId           `ic:"terms_and_conditions_id" json:"terms_and_conditions_id"`
	DecisionType         TermsAndConditionsDecisionType `ic:"decision_type" json:"decision_type"`
}

type UpsertTermsAndConditionsDecisionResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type TermsAndConditionsDecisionType struct {
	Accept *idl.Null `ic:"Accept,variant" json:"Accept,omitempty"`
	Reject *idl.Null `ic:"Reject,variant" json:"Reject,omitempty"`
}

type ListTeamsResponse struct {
	Ok  *[]Team   `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type ListOrgTeamsResponse struct {
	Ok  *[]OrgTeam `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError  `ic:"Err,variant" json:"Err,omitempty"`
}

type ListProjectTeamsResponse struct {
	Ok  *[]ProjectTeam `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError      `ic:"Err,variant" json:"Err,omitempty"`
}

type CreateTeamRequest struct {
	OrgId OrgId  `ic:"org_id" json:"org_id"`
	Name  string `ic:"name" json:"name"`
}

type CreateTeamResponse struct {
	Ok  *struct {
	Team Team `ic:"team" json:"team"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                           `ic:"Err,variant" json:"Err,omitempty"`
}

type GetTeamRequest struct {
	TeamId TeamId `ic:"team_id" json:"team_id"`
}

type GetTeamResponse struct {
	Ok  *struct {
	Team Team `ic:"team" json:"team"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                           `ic:"Err,variant" json:"Err,omitempty"`
}

type ListOrgTeamsRequest struct {
	OrgId OrgId `ic:"org_id" json:"org_id"`
}

type ListProjectTeamsRequest struct {
	ProjectId ProjectId `ic:"project_id" json:"project_id"`
}

type UpdateTeamRequest struct {
	TeamId TeamId `ic:"team_id" json:"team_id"`
	Name   string `ic:"name" json:"name"`
}

type UpdateTeamResponse struct {
	Ok  *struct {
	Team Team `ic:"team" json:"team"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                           `ic:"Err,variant" json:"Err,omitempty"`
}

type DeleteTeamRequest struct {
	TeamId TeamId `ic:"team_id" json:"team_id"`
}

type DeleteTeamResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type AddUserToTeamRequest struct {
	TeamId TeamId `ic:"team_id" json:"team_id"`
	UserId UserId `ic:"user_id" json:"user_id"`
}

type AddUserToTeamResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type RemoveUserFromTeamRequest struct {
	TeamId TeamId `ic:"team_id" json:"team_id"`
	UserId UserId `ic:"user_id" json:"user_id"`
}

type RemoveUserFromTeamResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type ListTeamUsersRequest struct {
	TeamId TeamId `ic:"team_id" json:"team_id"`
}

type TeamUser struct {
	Id            UserId  `ic:"id" json:"id"`
	Email         *string `ic:"email,omitempty" json:"email,omitempty"`
	EmailVerified bool    `ic:"email_verified" json:"email_verified"`
}

type ListTeamUsersResponse struct {
	Ok  *[]TeamUser `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError   `ic:"Err,variant" json:"Err,omitempty"`
}

type UpdateTeamOrgPermissionsRequest struct {
	TeamId      TeamId         `ic:"team_id" json:"team_id"`
	Permissions OrgPermissions `ic:"permissions" json:"permissions"`
}

type UpdateTeamOrgPermissionsResponse struct {
	Ok  *struct {
	Team OrgTeam `ic:"team" json:"team"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                              `ic:"Err,variant" json:"Err,omitempty"`
}

type Team struct {
	Id   TeamId `ic:"id" json:"id"`
	Name string `ic:"name" json:"name"`
}

type OrgTeam struct {
	Id          TeamId         `ic:"id" json:"id"`
	Name        string         `ic:"name" json:"name"`
	Permissions OrgPermissions `ic:"permissions" json:"permissions"`
}

type ProjectTeam struct {
	Id          TeamId             `ic:"id" json:"id"`
	Name        string             `ic:"name" json:"name"`
	Permissions ProjectPermissions `ic:"permissions" json:"permissions"`
}

type StaffPermissions struct {
	ReadAllOrgs  bool `ic:"read_all_orgs" json:"read_all_orgs"`
	WriteBilling bool `ic:"write_billing" json:"write_billing"`
	ManageUsers  bool `ic:"manage_users" json:"manage_users"`
	ReadMetrics  bool `ic:"read_metrics" json:"read_metrics"`
}

type GrantStaffPermissionsRequest struct {
	UserId      UserId           `ic:"user_id" json:"user_id"`
	Permissions StaffPermissions `ic:"permissions" json:"permissions"`
}

type GrantStaffPermissionsResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type RevokeStaffPermissionsRequest struct {
	UserId UserId `ic:"user_id" json:"user_id"`
}

type RevokeStaffPermissionsResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type GetMyStaffPermissionsRequest struct {
}

type GetMyStaffPermissionsResponse struct {
	Ok  **StaffPermissions `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError          `ic:"Err,variant" json:"Err,omitempty"`
}

type ListStaffRequest struct {
}

type ListStaffResponse struct {
	Ok  *[]StaffMember `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError      `ic:"Err,variant" json:"Err,omitempty"`
}

type StaffMember struct {
	UserId        UserId           `ic:"user_id" json:"user_id"`
	Email         *string          `ic:"email,omitempty" json:"email,omitempty"`
	EmailVerified bool             `ic:"email_verified" json:"email_verified"`
	Status        UserStatus       `ic:"status" json:"status"`
	Permissions   StaffPermissions `ic:"permissions" json:"permissions"`
}

type GrantServicePrincipalPermissionsRequest struct {
	ServicePrincipal principal.Principal `ic:"service_principal" json:"service_principal"`
	Permissions      StaffPermissions    `ic:"permissions" json:"permissions"`
}

type GrantServicePrincipalPermissionsResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type RevokeServicePrincipalPermissionsRequest struct {
	ServicePrincipal principal.Principal `ic:"service_principal" json:"service_principal"`
}

type RevokeServicePrincipalPermissionsResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type ListServicePrincipalsRequest struct {
}

type ListServicePrincipalsResponse struct {
	Ok  *struct {
	ServicePrincipals []ServicePrincipalEntry `ic:"service_principals" json:"service_principals"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                                                       `ic:"Err,variant" json:"Err,omitempty"`
}

type ServicePrincipalEntry struct {
	ServicePrincipal principal.Principal `ic:"service_principal" json:"service_principal"`
	Permissions      StaffPermissions    `ic:"permissions" json:"permissions"`
}

type CreateProposalRequest struct {
	ProjectId ProjectId          `ic:"project_id" json:"project_id"`
	Operation *ProposalOperation `ic:"operation,omitempty" json:"operation,omitempty"`
}

type CreateProposalResponse struct {
	Ok  *Proposal `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type GetProposalRequest struct {
	ProposalId ProposalId `ic:"proposal_id" json:"proposal_id"`
}

type GetProposalResponse struct {
	Ok  *Proposal `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type ListProjectProposalsRequest struct {
	ProjectId    ProjectId               `ic:"project_id" json:"project_id"`
	StatusFilter *[]ProposalStatusFilter `ic:"status_filter,omitempty" json:"status_filter,omitempty"`
	After        *ProposalId             `ic:"after,omitempty" json:"after,omitempty"`
	Limit        *uint64                 `ic:"limit,omitempty" json:"limit,omitempty"`
}

type ListProjectProposalsResponse struct {
	Ok  *struct {
	Proposals  []Proposal  `ic:"proposals" json:"proposals"`
	NextCursor *ProposalId `ic:"next_cursor,omitempty" json:"next_cursor,omitempty"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                                          `ic:"Err,variant" json:"Err,omitempty"`
}

type ProposalStatusFilter struct {
	Open            *struct {
} `ic:"Open,variant" json:"Open,omitempty"`
	PendingApproval *struct {
} `ic:"PendingApproval,variant" json:"PendingApproval,omitempty"`
	Rejected        *struct {
} `ic:"Rejected,variant" json:"Rejected,omitempty"`
	Cancelled       *struct {
} `ic:"Cancelled,variant" json:"Cancelled,omitempty"`
	Executing       *struct {
} `ic:"Executing,variant" json:"Executing,omitempty"`
	Executed        *struct {
} `ic:"Executed,variant" json:"Executed,omitempty"`
	Failed          *struct {
} `ic:"Failed,variant" json:"Failed,omitempty"`
}

type VoteProposalRequest struct {
	ProposalId ProposalId `ic:"proposal_id" json:"proposal_id"`
	Vote       Vote       `ic:"vote" json:"vote"`
}

type VoteProposalResponse struct {
	Ok  *Proposal `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type CancelProposalRequest struct {
	ProposalId ProposalId `ic:"proposal_id" json:"proposal_id"`
}

type CancelProposalResponse struct {
	Ok  *Proposal `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type Proposal struct {
	Id             ProposalId         `ic:"id" json:"id"`
	ProjectId      ProjectId          `ic:"project_id" json:"project_id"`
	ProposerId     UserId             `ic:"proposer_id" json:"proposer_id"`
	Status         *ProposalStatus    `ic:"status,omitempty" json:"status,omitempty"`
	Operation      *ProposalOperation `ic:"operation,omitempty" json:"operation,omitempty"`
	CreatedAtNanos *uint64            `ic:"created_at_nanos,omitempty" json:"created_at_nanos,omitempty"`
	UpdatedAtNanos *uint64            `ic:"updated_at_nanos,omitempty" json:"updated_at_nanos,omitempty"`
}

type ProposalStatus struct {
	Open            *struct {
}                                                  `ic:"Open,variant" json:"Open,omitempty"`
	PendingApproval *struct {
	Threshold uint32         `ic:"threshold" json:"threshold"`
	Approvers []UserId       `ic:"approvers" json:"approvers"`
	Votes     []ProposalVote `ic:"votes" json:"votes"`
} `ic:"PendingApproval,variant" json:"PendingApproval,omitempty"`
	Rejected        *struct {
}                                                  `ic:"Rejected,variant" json:"Rejected,omitempty"`
	Cancelled       *struct {
}                                                  `ic:"Cancelled,variant" json:"Cancelled,omitempty"`
	Executing       *struct {
}                                                  `ic:"Executing,variant" json:"Executing,omitempty"`
	Executed        *struct {
}                                                  `ic:"Executed,variant" json:"Executed,omitempty"`
	Failed          *struct {
	Message string `ic:"message" json:"message"`
}    `ic:"Failed,variant" json:"Failed,omitempty"`
}

type ProposalVote struct {
	Voter UserId `ic:"voter" json:"voter"`
	Vote  Vote   `ic:"vote" json:"vote"`
}

type Vote struct {
	Approve *struct {
} `ic:"Approve,variant" json:"Approve,omitempty"`
	Reject  *struct {
} `ic:"Reject,variant" json:"Reject,omitempty"`
}

type ProposalOperation struct {
	CreateCanister        *struct {
}                                                                  `ic:"CreateCanister,variant" json:"CreateCanister,omitempty"`
	AddCanisterController *struct {
	CanisterId   principal.Principal `ic:"canister_id" json:"canister_id"`
	ControllerId principal.Principal `ic:"controller_id" json:"controller_id"`
} `ic:"AddCanisterController,variant" json:"AddCanisterController,omitempty"`
}

type ListMyProjectsRequest struct {
}

type ListMyProjectsResponse struct {
	Ok  *struct {
	Projects []Project `ic:"projects" json:"projects"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                            `ic:"Err,variant" json:"Err,omitempty"`
}

type ListOrgProjectsRequest struct {
	OrgId OrgId `ic:"org_id" json:"org_id"`
}

type ListOrgProjectsResponse struct {
	Ok  *struct {
	Projects []Project `ic:"projects" json:"projects"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                            `ic:"Err,variant" json:"Err,omitempty"`
}

type CreateProjectRequest struct {
	OrgId OrgId  `ic:"org_id" json:"org_id"`
	Name  string `ic:"name" json:"name"`
}

type ProjectResponse struct {
	Ok  *struct {
	Project Project `ic:"project" json:"project"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                       `ic:"Err,variant" json:"Err,omitempty"`
}

type CreateProjectResponse = ProjectResponse

type GetProjectResponse = ProjectResponse

type UpdateProjectResponse = ProjectResponse

type GetProjectRequest struct {
	ProjectId ProjectId `ic:"project_id" json:"project_id"`
}

type UpdateProjectRequest struct {
	ProjectId ProjectId `ic:"project_id" json:"project_id"`
	Name      string    `ic:"name" json:"name"`
}

type DeleteProjectRequest struct {
	ProjectId ProjectId `ic:"project_id" json:"project_id"`
}

type DeleteProjectResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type AddTeamToProjectRequest struct {
	ProjectId ProjectId `ic:"project_id" json:"project_id"`
	TeamId    TeamId    `ic:"team_id" json:"team_id"`
}

type AddTeamToProjectResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type RemoveTeamFromProjectRequest struct {
	ProjectId ProjectId `ic:"project_id" json:"project_id"`
	TeamId    TeamId    `ic:"team_id" json:"team_id"`
}

type RemoveTeamFromProjectResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type UpdateTeamProjectPermissionsRequest struct {
	ProjectId   ProjectId          `ic:"project_id" json:"project_id"`
	TeamId      TeamId             `ic:"team_id" json:"team_id"`
	Permissions ProjectPermissions `ic:"permissions" json:"permissions"`
}

type UpdateTeamProjectPermissionsResponse struct {
	Ok  *struct {
	Team ProjectTeam `ic:"team" json:"team"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                  `ic:"Err,variant" json:"Err,omitempty"`
}

type Project struct {
	OrgId           OrgId              `ic:"org_id" json:"org_id"`
	Id              ProjectId          `ic:"id" json:"id"`
	Name            string             `ic:"name" json:"name"`
	YourPermissions ProjectPermissions `ic:"your_permissions" json:"your_permissions"`
}

type RegisterLinkCodeRequest struct {
	Code            string              `ic:"code" json:"code"`
	TargetPrincipal principal.Principal `ic:"target_principal" json:"target_principal"`
}

type RegisterLinkCodeResponse struct {
	Ok  *struct {
	ExpiresAtNanos uint64 `ic:"expires_at_nanos" json:"expires_at_nanos"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                               `ic:"Err,variant" json:"Err,omitempty"`
}

type LinkMyPrincipalRequest struct {
	Code string `ic:"code" json:"code"`
}

type LinkMyPrincipalResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type UnlinkMyPrincipalRequest struct {
	Principal principal.Principal `ic:"principal" json:"principal"`
}

type UnlinkMyPrincipalResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type ListMyLinkedPrincipalsRequest struct {
}

type LinkedPrincipal struct {
	Principal principal.Principal `ic:"principal" json:"principal"`
	Name      *string             `ic:"name,omitempty" json:"name,omitempty"`
}

type ListMyLinkedPrincipalsResponse struct {
	Ok  *struct {
	Principals []LinkedPrincipal `ic:"principals" json:"principals"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                          `ic:"Err,variant" json:"Err,omitempty"`
}

type SetMyPrincipalNameRequest struct {
	Principal principal.Principal `ic:"principal" json:"principal"`
	Name      *string             `ic:"name,omitempty" json:"name,omitempty"`
}

type SetMyPrincipalNameResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type PendingLinkCode struct {
	Code            string              `ic:"code" json:"code"`
	ExpiresAtNanos  uint64              `ic:"expires_at_nanos" json:"expires_at_nanos"`
	TargetPrincipal principal.Principal `ic:"target_principal" json:"target_principal"`
}

type GetMyPendingLinkCodeRequest struct {
}

type GetMyPendingLinkCodeResponse struct {
	Ok  *struct {
	Code *PendingLinkCode `ic:"code,omitempty" json:"code,omitempty"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                           `ic:"Err,variant" json:"Err,omitempty"`
}

type RevokeMyLinkCodeRequest struct {
}

type RevokeMyLinkCodeResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type AdminLinkPrincipalRequest struct {
	UserId    UserId              `ic:"user_id" json:"user_id"`
	Principal principal.Principal `ic:"principal" json:"principal"`
}

type AdminLinkPrincipalResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type AdminUnlinkPrincipalRequest struct {
	UserId    UserId              `ic:"user_id" json:"user_id"`
	Principal principal.Principal `ic:"principal" json:"principal"`
}

type AdminUnlinkPrincipalResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type AdminListLinkedPrincipalsRequest struct {
	UserId UserId `ic:"user_id" json:"user_id"`
}

type AdminListLinkedPrincipalsResponse struct {
	Ok  *struct {
	Principals []principal.Principal `ic:"principals" json:"principals"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                              `ic:"Err,variant" json:"Err,omitempty"`
}

type RecoverAccountByEmailRequest struct {
	Token string `ic:"token" json:"token"`
}

type RecoverAccountByEmailResponse struct {
	Ok  *struct {
}     `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *RejectionError `ic:"Err,variant" json:"Err,omitempty"`
}

type RejectionReason struct {
	Expired           *idl.Null `ic:"Expired,variant" json:"Expired,omitempty"`
	Invalid           *idl.Null `ic:"Invalid,variant" json:"Invalid,omitempty"`
	WrongPurpose      *idl.Null `ic:"WrongPurpose,variant" json:"WrongPurpose,omitempty"`
	EmailMismatch     *idl.Null `ic:"EmailMismatch,variant" json:"EmailMismatch,omitempty"`
	ProfileNotFound   *idl.Null `ic:"ProfileNotFound,variant" json:"ProfileNotFound,omitempty"`
	NoVerifiedAccount *idl.Null `ic:"NoVerifiedAccount,variant" json:"NoVerifiedAccount,omitempty"`
}

type RejectionError struct {
	Message string           `ic:"message" json:"message"`
	Reason  *RejectionReason `ic:"reason,omitempty" json:"reason,omitempty"`
}

type PlanTier struct {
	Free       *idl.Null `ic:"Free,variant" json:"Free,omitempty"`
	Pro        *idl.Null `ic:"Pro,variant" json:"Pro,omitempty"`
	Enterprise *idl.Null `ic:"Enterprise,variant" json:"Enterprise,omitempty"`
}

type SetOrgBillingPlanRequest struct {
	OrgId OrgId    `ic:"org_id" json:"org_id"`
	Tier  PlanTier `ic:"tier" json:"tier"`
}

type SetOrgBillingPlanResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type GetOrgBillingPlanRequest struct {
	OrgId OrgId `ic:"org_id" json:"org_id"`
}

type GetOrgBillingPlanResponseData struct {
	Tier            PlanTier `ic:"tier" json:"tier"`
	MaxCanisters    uint32   `ic:"max_canisters" json:"max_canisters"`
	CanistersUsed   uint32   `ic:"canisters_used" json:"canisters_used"`
	MaxStorageBytes *uint64  `ic:"max_storage_bytes,omitempty" json:"max_storage_bytes,omitempty"`
}

type GetOrgBillingPlanResponse struct {
	Ok  *GetOrgBillingPlanResponseData `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                      `ic:"Err,variant" json:"Err,omitempty"`
}

type MyOrgBillingPlan struct {
	OrgId           OrgId    `ic:"org_id" json:"org_id"`
	Tier            PlanTier `ic:"tier" json:"tier"`
	MaxCanisters    uint32   `ic:"max_canisters" json:"max_canisters"`
	CanistersUsed   uint32   `ic:"canisters_used" json:"canisters_used"`
	MaxStorageBytes *uint64  `ic:"max_storage_bytes,omitempty" json:"max_storage_bytes,omitempty"`
}

type ListMyOrgBillingPlansResponse struct {
	Ok  *[]MyOrgBillingPlan `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError           `ic:"Err,variant" json:"Err,omitempty"`
}

type ListMyOrganizationsResponse struct {
	Ok  *[]Organization `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError       `ic:"Err,variant" json:"Err,omitempty"`
}

type ListOrganizationsRequest struct {
	After *string `ic:"after,omitempty" json:"after,omitempty"`
	Limit *uint32 `ic:"limit,omitempty" json:"limit,omitempty"`
}

type AdminOrganization struct {
	Id          OrgId    `ic:"id" json:"id"`
	Name        string   `ic:"name" json:"name"`
	Tier        PlanTier `ic:"tier" json:"tier"`
	MemberCount uint32   `ic:"member_count" json:"member_count"`
}

type ListOrganizationsResponse struct {
	Ok  *struct {
	Organizations []AdminOrganization `ic:"organizations" json:"organizations"`
	NextCursor    *string             `ic:"next_cursor,omitempty" json:"next_cursor,omitempty"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                                                     `ic:"Err,variant" json:"Err,omitempty"`
}

type CreateOrganizationRequest struct {
	Name string `ic:"name" json:"name"`
}

type CreateOrganizationResponse struct {
	Ok  *struct {
	Organization Organization `ic:"organization" json:"organization"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                           `ic:"Err,variant" json:"Err,omitempty"`
}

type GetOrganizationRequest struct {
	OrgId OrgId `ic:"org_id" json:"org_id"`
}

type GetOrganizationResponse struct {
	Ok  *struct {
	Organization Organization `ic:"organization" json:"organization"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                           `ic:"Err,variant" json:"Err,omitempty"`
}

type UpdateOrganizationRequest struct {
	OrgId OrgId  `ic:"org_id" json:"org_id"`
	Name  string `ic:"name" json:"name"`
}

type UpdateOrganizationResponse struct {
	Ok  *struct {
	Organization Organization `ic:"organization" json:"organization"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                           `ic:"Err,variant" json:"Err,omitempty"`
}

type DeleteOrganizationRequest struct {
	OrgId OrgId `ic:"org_id" json:"org_id"`
}

type DeleteOrganizationResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type ListOrgUsersRequest struct {
	OrgId OrgId `ic:"org_id" json:"org_id"`
}

type OrgUser struct {
	Id            UserId  `ic:"id" json:"id"`
	Email         *string `ic:"email,omitempty" json:"email,omitempty"`
	EmailVerified bool    `ic:"email_verified" json:"email_verified"`
	Teams         []Team  `ic:"teams" json:"teams"`
	IsOrgAdmin    bool    `ic:"is_org_admin" json:"is_org_admin"`
}

type ListOrgUsersResponse struct {
	Ok  *[]OrgUser `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError  `ic:"Err,variant" json:"Err,omitempty"`
}

type Organization struct {
	Id              OrgId          `ic:"id" json:"id"`
	Name            string         `ic:"name" json:"name"`
	YourPermissions OrgPermissions `ic:"your_permissions" json:"your_permissions"`
}

type OrgPermissions struct {
	OrgAdmin      bool `ic:"org_admin" json:"org_admin"`
	MemberManage  bool `ic:"member_manage" json:"member_manage"`
	TeamManage    bool `ic:"team_manage" json:"team_manage"`
	ProjectCreate bool `ic:"project_create" json:"project_create"`
	BillingManage bool `ic:"billing_manage" json:"billing_manage"`
}

type ProjectPermissions struct {
	ProjectAdmin         bool `ic:"project_admin" json:"project_admin"`
	CanisterManage       bool `ic:"canister_manage" json:"canister_manage"`
	ProposalCreate       bool `ic:"proposal_create" json:"proposal_create"`
	ProposalApprove      bool `ic:"proposal_approve" json:"proposal_approve"`
	CanisterOperate      bool `ic:"canister_operate" json:"canister_operate"`
	CanisterRead         bool `ic:"canister_read" json:"canister_read"`
	ApprovalPolicyManage bool `ic:"approval_policy_manage" json:"approval_policy_manage"`
	ProjectSettings      bool `ic:"project_settings" json:"project_settings"`
}

type GetMetricsRequest struct {
}

type GetMetricsResponse struct {
	Ok  *struct {
	EntryCounts      []EntryCount   `ic:"entry_counts" json:"entry_counts"`
	MemoryRegions    []MemoryRegion `ic:"memory_regions" json:"memory_regions"`
	TotalStablePages uint64         `ic:"total_stable_pages" json:"total_stable_pages"`
	TotalStableBytes uint64         `ic:"total_stable_bytes" json:"total_stable_bytes"`
	CyclesBalance    idl.Nat        `ic:"cycles_balance" json:"cycles_balance"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                                             `ic:"Err,variant" json:"Err,omitempty"`
}

type EntryCount struct {
	Name  string `ic:"name" json:"name"`
	Count uint64 `ic:"count" json:"count"`
}

type MemoryRegion struct {
	Name     string `ic:"name" json:"name"`
	MemoryId uint8  `ic:"memory_id" json:"memory_id"`
	Pages    uint64 `ic:"pages" json:"pages"`
	Bytes    uint64 `ic:"bytes" json:"bytes"`
}

type InviteTarget struct {
	Email     *string              `ic:"Email,variant" json:"Email,omitempty"`
	UserId    *UserId              `ic:"UserId,variant" json:"UserId,omitempty"`
	Principal *principal.Principal `ic:"Principal,variant" json:"Principal,omitempty"`
}

type InviteStatus struct {
	Pending  *idl.Null `ic:"Pending,variant" json:"Pending,omitempty"`
	Accepted *idl.Null `ic:"Accepted,variant" json:"Accepted,omitempty"`
	Declined *idl.Null `ic:"Declined,variant" json:"Declined,omitempty"`
	Revoked  *idl.Null `ic:"Revoked,variant" json:"Revoked,omitempty"`
}

type OrgInvite struct {
	Id          InviteId     `ic:"id" json:"id"`
	OrgId       OrgId        `ic:"org_id" json:"org_id"`
	OrgName     string       `ic:"org_name" json:"org_name"`
	CreatedBy   UserId       `ic:"created_by" json:"created_by"`
	CreatedAtNs uint64       `ic:"created_at_ns" json:"created_at_ns"`
	ExpiresAtNs uint64       `ic:"expires_at_ns" json:"expires_at_ns"`
	Target      InviteTarget `ic:"target" json:"target"`
	Status      InviteStatus `ic:"status" json:"status"`
}

type CreateOrgInviteRequest struct {
	OrgId  OrgId        `ic:"org_id" json:"org_id"`
	Target InviteTarget `ic:"target" json:"target"`
}

type CreateOrgInviteResponse struct {
	Ok  *struct {
	Invite OrgInvite `ic:"invite" json:"invite"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                      `ic:"Err,variant" json:"Err,omitempty"`
}

type ListOrgInvitesRequest struct {
	OrgId OrgId `ic:"org_id" json:"org_id"`
}

type ListOrgInvitesResponse struct {
	Ok  *[]OrgInvite `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError    `ic:"Err,variant" json:"Err,omitempty"`
}

type ListMyInvitesResponse struct {
	Ok  *[]OrgInvite `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError    `ic:"Err,variant" json:"Err,omitempty"`
}

type RevokeOrgInviteRequest struct {
	InviteId InviteId `ic:"invite_id" json:"invite_id"`
}

type RevokeOrgInviteResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type AcceptOrgInviteRequest struct {
	InviteId InviteId `ic:"invite_id" json:"invite_id"`
}

type AcceptOrgInviteResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type DeclineOrgInviteRequest struct {
	InviteId InviteId `ic:"invite_id" json:"invite_id"`
}

type DeclineOrgInviteResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type HttpRequest struct {
	Url                string                                 `ic:"url" json:"url"`
	Method             string                                 `ic:"method" json:"method"`
	Body               []byte                                 `ic:"body" json:"body"`
	Headers            []struct {
	Field0 string `ic:"0,tuple" json:"0"`
	Field1 string `ic:"1,tuple" json:"1"`
} `ic:"headers" json:"headers"`
	CertificateVersion *uint16                                `ic:"certificate_version,omitempty" json:"certificate_version,omitempty"`
}

type HttpResponse struct {
	Body       []byte                                 `ic:"body" json:"body"`
	Headers    []struct {
	Field0 string `ic:"0,tuple" json:"0"`
	Field1 string `ic:"1,tuple" json:"1"`
} `ic:"headers" json:"headers"`
	Upgrade    *bool                                  `ic:"upgrade,omitempty" json:"upgrade,omitempty"`
	StatusCode uint16                                 `ic:"status_code" json:"status_code"`
}

type BlockIndex = idl.Nat

type CreateCanisterArgs struct {
	FromSubaccount *[]uint8               `ic:"from_subaccount,omitempty" json:"from_subaccount,omitempty"`
	CreatedAtTime  *uint64                `ic:"created_at_time,omitempty" json:"created_at_time,omitempty"`
	Amount         idl.Nat                `ic:"amount" json:"amount"`
	CreationArgs   *CmcCreateCanisterArgs `ic:"creation_args,omitempty" json:"creation_args,omitempty"`
}

type LogVisibility struct {
	Controllers    *idl.Null              `ic:"controllers,variant" json:"controllers,omitempty"`
	Public         *idl.Null              `ic:"public,variant" json:"public,omitempty"`
	AllowedViewers *[]principal.Principal `ic:"allowed_viewers,variant" json:"allowed_viewers,omitempty"`
}

type EnvironmentVariable struct {
	Name  string `ic:"name" json:"name"`
	Value string `ic:"value" json:"value"`
}

type CmcCreateCanisterArgs struct {
	Settings        *CanisterSettings `ic:"settings,omitempty" json:"settings,omitempty"`
	SubnetSelection *SubnetSelection  `ic:"subnet_selection,omitempty" json:"subnet_selection,omitempty"`
}

type CanisterSettings struct {
	Controllers          *[]principal.Principal `ic:"controllers,omitempty" json:"controllers,omitempty"`
	ComputeAllocation    *idl.Nat               `ic:"compute_allocation,omitempty" json:"compute_allocation,omitempty"`
	MemoryAllocation     *idl.Nat               `ic:"memory_allocation,omitempty" json:"memory_allocation,omitempty"`
	FreezingThreshold    *idl.Nat               `ic:"freezing_threshold,omitempty" json:"freezing_threshold,omitempty"`
	ReservedCyclesLimit  *idl.Nat               `ic:"reserved_cycles_limit,omitempty" json:"reserved_cycles_limit,omitempty"`
	WasmMemoryLimit      *idl.Nat               `ic:"wasm_memory_limit,omitempty" json:"wasm_memory_limit,omitempty"`
	WasmMemoryThreshold  *idl.Nat               `ic:"wasm_memory_threshold,omitempty" json:"wasm_memory_threshold,omitempty"`
	LogVisibility        *LogVisibility         `ic:"log_visibility,omitempty" json:"log_visibility,omitempty"`
	EnvironmentVariables *[]EnvironmentVariable `ic:"environment_variables,omitempty" json:"environment_variables,omitempty"`
}

type CreateCanisterSuccess struct {
	BlockId    BlockIndex          `ic:"block_id" json:"block_id"`
	CanisterId principal.Principal `ic:"canister_id" json:"canister_id"`
}

type CreateCanisterError struct {
	InsufficientFunds      *struct {
	Balance idl.Nat `ic:"balance" json:"balance"`
}                                   `ic:"InsufficientFunds,variant" json:"InsufficientFunds,omitempty"`
	TooOld                 *idl.Null                                                                                    `ic:"TooOld,variant" json:"TooOld,omitempty"`
	CreatedInFuture        *struct {
	LedgerTime uint64 `ic:"ledger_time" json:"ledger_time"`
}                         `ic:"CreatedInFuture,variant" json:"CreatedInFuture,omitempty"`
	TemporarilyUnavailable *idl.Null                                                                                    `ic:"TemporarilyUnavailable,variant" json:"TemporarilyUnavailable,omitempty"`
	Duplicate              *struct {
	DuplicateOf idl.Nat              `ic:"duplicate_of" json:"duplicate_of"`
	CanisterId  *principal.Principal `ic:"canister_id,omitempty" json:"canister_id,omitempty"`
} `ic:"Duplicate,variant" json:"Duplicate,omitempty"`
	FailedToCreate         *struct {
	FeeBlock    *BlockIndex `ic:"fee_block,omitempty" json:"fee_block,omitempty"`
	RefundBlock *BlockIndex `ic:"refund_block,omitempty" json:"refund_block,omitempty"`
	Error       string      `ic:"error" json:"error"`
} `ic:"FailedToCreate,variant" json:"FailedToCreate,omitempty"`
	GenericError           *struct {
	Message   string  `ic:"message" json:"message"`
	ErrorCode idl.Nat `ic:"error_code" json:"error_code"`
} `ic:"GenericError,variant" json:"GenericError,omitempty"`
}

type SubnetSelection struct {
	Subnet *struct {
	Subnet principal.Principal `ic:"subnet" json:"subnet"`
} `ic:"Subnet,variant" json:"Subnet,omitempty"`
	Filter *SubnetFilter                                            `ic:"Filter,variant" json:"Filter,omitempty"`
}

type SubnetFilter struct {
	SubnetType *string `ic:"subnet_type,omitempty" json:"subnet_type,omitempty"`
}

type ListMyCanistersRequest struct {
	ProjectId ProjectId `ic:"project_id" json:"project_id"`
}

type ListMyCanistersResponse struct {
	Ok  *[]Canister `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError   `ic:"Err,variant" json:"Err,omitempty"`
}

type RemoveMyCanisterRequest struct {
	CanisterId CanisterId `ic:"canister_id" json:"canister_id"`
}

type RemoveMyCanisterResponse struct {
	Ok  *idl.Null `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type UpdateMyCanisterNameRequest struct {
	CanisterId CanisterId `ic:"canister_id" json:"canister_id"`
	Name       *string    `ic:"name,omitempty" json:"name,omitempty"`
}

type UpdateMyCanisterNameResponse struct {
	Ok  *idl.Null `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type StartMyCanisterRequest struct {
	CanisterId CanisterId `ic:"canister_id" json:"canister_id"`
}

type StartMyCanisterResponse struct {
	Ok  *idl.Null `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type StopMyCanisterRequest struct {
	CanisterId CanisterId `ic:"canister_id" json:"canister_id"`
}

type StopMyCanisterResponse struct {
	Ok  *idl.Null `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type ListAllCanistersRequest struct {
	Limit *uint64 `ic:"limit,omitempty" json:"limit,omitempty"`
	Page  *uint64 `ic:"page,omitempty" json:"page,omitempty"`
}

type ListAllCanistersResponse struct {
	Ok  *struct {
	Canisters []CanisterWithOwner    `ic:"canisters" json:"canisters"`
	Meta      PaginationMetaResponse `ic:"meta" json:"meta"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                            `ic:"Err,variant" json:"Err,omitempty"`
}

type CanisterWithOwner struct {
	Id            CanisterId `ic:"id" json:"id"`
	PrincipalId   string     `ic:"principal_id" json:"principal_id"`
	UserId        UserId     `ic:"user_id" json:"user_id"`
	Email         *string    `ic:"email,omitempty" json:"email,omitempty"`
	EmailVerified bool       `ic:"email_verified" json:"email_verified"`
	DeletedAt     *uint64    `ic:"deleted_at,omitempty" json:"deleted_at,omitempty"`
}

type PaginationMetaResponse struct {
	Limit      uint64 `ic:"limit" json:"limit"`
	Page       uint64 `ic:"page" json:"page"`
	TotalItems uint64 `ic:"total_items" json:"total_items"`
	TotalPages uint64 `ic:"total_pages" json:"total_pages"`
}

type Canister struct {
	Id          CanisterId    `ic:"id" json:"id"`
	PrincipalId string        `ic:"principal_id" json:"principal_id"`
	Name        *string       `ic:"name,omitempty" json:"name,omitempty"`
	State       CanisterState `ic:"state" json:"state"`
	DeletedAt   *uint64       `ic:"deleted_at,omitempty" json:"deleted_at,omitempty"`
}

type CanisterState struct {
	Accessible   *CanisterInfo `ic:"Accessible,variant" json:"Accessible,omitempty"`
	Inaccessible *idl.Null     `ic:"Inaccessible,variant" json:"Inaccessible,omitempty"`
	Deleted      *idl.Null     `ic:"Deleted,variant" json:"Deleted,omitempty"`
}

type CanisterInfo struct {
	Status                 CanisterStatus           `ic:"status" json:"status"`
	ReadyForMigration      bool                     `ic:"ready_for_migration" json:"ready_for_migration"`
	Version                uint64                   `ic:"version" json:"version"`
	Settings               DefiniteCanisterSettings `ic:"settings" json:"settings"`
	ModuleHash             *[]byte                  `ic:"module_hash,omitempty" json:"module_hash,omitempty"`
	MemorySize             idl.Nat                  `ic:"memory_size" json:"memory_size"`
	MemoryMetrics          MemoryMetrics            `ic:"memory_metrics" json:"memory_metrics"`
	Cycles                 idl.Nat                  `ic:"cycles" json:"cycles"`
	ReservedCycles         idl.Nat                  `ic:"reserved_cycles" json:"reserved_cycles"`
	IdleCyclesBurnedPerDay idl.Nat                  `ic:"idle_cycles_burned_per_day" json:"idle_cycles_burned_per_day"`
	QueryStats             QueryStats               `ic:"query_stats" json:"query_stats"`
}

type CanisterStatus struct {
	Running  *idl.Null `ic:"Running,variant" json:"Running,omitempty"`
	Stopping *idl.Null `ic:"Stopping,variant" json:"Stopping,omitempty"`
	Stopped  *idl.Null `ic:"Stopped,variant" json:"Stopped,omitempty"`
}

type QueryStats struct {
	NumCallsTotal             idl.Nat `ic:"num_calls_total" json:"num_calls_total"`
	NumInstructionsTotal      idl.Nat `ic:"num_instructions_total" json:"num_instructions_total"`
	RequestPayloadBytesTotal  idl.Nat `ic:"request_payload_bytes_total" json:"request_payload_bytes_total"`
	ResponsePayloadBytesTotal idl.Nat `ic:"response_payload_bytes_total" json:"response_payload_bytes_total"`
}

type MemoryMetrics struct {
	WasmMemorySize      idl.Nat `ic:"wasm_memory_size" json:"wasm_memory_size"`
	StableMemorySize    idl.Nat `ic:"stable_memory_size" json:"stable_memory_size"`
	GlobalMemorySize    idl.Nat `ic:"global_memory_size" json:"global_memory_size"`
	WasmBinarySize      idl.Nat `ic:"wasm_binary_size" json:"wasm_binary_size"`
	CustomSectionsSize  idl.Nat `ic:"custom_sections_size" json:"custom_sections_size"`
	CanisterHistorySize idl.Nat `ic:"canister_history_size" json:"canister_history_size"`
	WasmChunkStoreSize  idl.Nat `ic:"wasm_chunk_store_size" json:"wasm_chunk_store_size"`
	SnapshotsSize       idl.Nat `ic:"snapshots_size" json:"snapshots_size"`
}

type DefiniteCanisterSettings struct {
	Controllers          []principal.Principal         `ic:"controllers" json:"controllers"`
	ComputeAllocation    idl.Nat                       `ic:"compute_allocation" json:"compute_allocation"`
	MemoryAllocation     idl.Nat                       `ic:"memory_allocation" json:"memory_allocation"`
	FreezingThreshold    idl.Nat                       `ic:"freezing_threshold" json:"freezing_threshold"`
	ReservedCyclesLimit  idl.Nat                       `ic:"reserved_cycles_limit" json:"reserved_cycles_limit"`
	LogVisibility        CanisterLogVisibility         `ic:"log_visibility" json:"log_visibility"`
	WasmMemoryLimit      idl.Nat                       `ic:"wasm_memory_limit" json:"wasm_memory_limit"`
	WasmMemoryThreshold  idl.Nat                       `ic:"wasm_memory_threshold" json:"wasm_memory_threshold"`
	EnvironmentVariables []CanisterEnvironmentVariable `ic:"environment_variables" json:"environment_variables"`
}

type CanisterLogVisibility struct {
	Controllers    *idl.Null              `ic:"Controllers,variant" json:"Controllers,omitempty"`
	Public         *idl.Null              `ic:"Public,variant" json:"Public,omitempty"`
	AllowedViewers *[]principal.Principal `ic:"AllowedViewers,variant" json:"AllowedViewers,omitempty"`
}

type CanisterEnvironmentVariable struct {
	Name  string `ic:"name" json:"name"`
	Value string `ic:"value" json:"value"`
}

type ListUserCanistersRequest struct {
	UserId UserId `ic:"user_id" json:"user_id"`
}

type ListUserCanistersResponse struct {
	Ok  *struct {
	Canisters []Canister `ic:"canisters" json:"canisters"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                `ic:"Err,variant" json:"Err,omitempty"`
}

type ListUserReadableCanisterPrincipalsRequest struct {
	UserPrincipal principal.Principal `ic:"user_principal" json:"user_principal"`
}

type ListUserReadableCanisterPrincipalsResponse struct {
	Ok  *struct {
	CanisterPrincipals []principal.Principal `ic:"canister_principals" json:"canister_principals"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                                                        `ic:"Err,variant" json:"Err,omitempty"`
}

type ParentChildMapping struct {
	ChildCanisterId  principal.Principal `ic:"child_canister_id" json:"child_canister_id"`
	ParentCanisterId principal.Principal `ic:"parent_canister_id" json:"parent_canister_id"`
}

type AddChildCanistersRequest struct {
	ParentChildMappings []ParentChildMapping `ic:"parent_child_mappings" json:"parent_child_mappings"`
}

type TrackChildCanistersResponse struct {
	Ok  *struct {
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError `ic:"Err,variant" json:"Err,omitempty"`
}

type ListProjectApprovalPoliciesResponse struct {
	Ok  *struct {
	ApprovalPolicies []ApprovalPolicy `ic:"approval_policies" json:"approval_policies"`
} `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError                                                                             `ic:"Err,variant" json:"Err,omitempty"`
}

type ListProjectApprovalPoliciesRequest struct {
	ProjectId ProjectId `ic:"project_id" json:"project_id"`
}

type UpsertApprovalPolicyRequest struct {
	ProjectId     ProjectId     `ic:"project_id" json:"project_id"`
	OperationType OperationType `ic:"operation_type" json:"operation_type"`
	PolicyType    PolicyType    `ic:"policy_type" json:"policy_type"`
}

type UpsertApprovalPolicyResponse struct {
	Ok  *ApprovalPolicy `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *ApiError       `ic:"Err,variant" json:"Err,omitempty"`
}

type ApprovalPolicy struct {
	Id            ApprovalPolicyId `ic:"id" json:"id"`
	OperationType OperationType    `ic:"operation_type" json:"operation_type"`
	PolicyType    PolicyType       `ic:"policy_type" json:"policy_type"`
}

type OperationType struct {
	CreateCanister        *struct {
} `ic:"CreateCanister,variant" json:"CreateCanister,omitempty"`
	AddCanisterController *struct {
} `ic:"AddCanisterController,variant" json:"AddCanisterController,omitempty"`
}

type PolicyType struct {
	AutoApprove *struct {
}                                          `ic:"AutoApprove,variant" json:"AutoApprove,omitempty"`
	FixedQuorum *struct {
	Threshold uint32 `ic:"threshold" json:"threshold"`
} `ic:"FixedQuorum,variant" json:"FixedQuorum,omitempty"`
}

type ApiError struct {
	Code    *ApiErrorCode `ic:"code,omitempty" json:"code,omitempty"`
	Message string        `ic:"message" json:"message"`
}

type ApiErrorCode struct {
	Unauthenticated *struct {
} `ic:"Unauthenticated,variant" json:"Unauthenticated,omitempty"`
	Unauthorized    *struct {
} `ic:"Unauthorized,variant" json:"Unauthorized,omitempty"`
	DependencyError *struct {
} `ic:"DependencyError,variant" json:"DependencyError,omitempty"`
	InternalError   *struct {
} `ic:"InternalError,variant" json:"InternalError,omitempty"`
	ClientError     *struct {
} `ic:"ClientError,variant" json:"ClientError,omitempty"`
	QuotaExceeded   *struct {
} `ic:"QuotaExceeded,variant" json:"QuotaExceeded,omitempty"`
}

type UserId = string

type OrgId = string

type TeamId = string

type ProjectId = string

type CanisterId = string

type ProposalId = string

type InviteId = string

type TrustedPartnerId = string

type ApprovalPolicyId = string

type TermsAndConditionsId = string

type TermsAndConditionsDecisionId = string

// BackendAgent is a client for the "backend" canister.
type BackendAgent struct {
    *agent.Agent
    CanisterId principal.Principal
}

// NewBackendAgent creates a new agent for the "backend" canister.
func NewBackendAgent(canisterId principal.Principal, config agent.Config) (*BackendAgent, error) {
    a, err := agent.New(config)
    if err != nil {
        return nil, err
    }
    return &BackendAgent{
        Agent:      a,
        CanisterId: canisterId,
    }, nil
}

// RecordUsage calls the "record_usage" method on the "backend" canister.
func (a BackendAgent) RecordUsage(arg0 RecordUsageRequest) (*RecordUsageResponse, error) {
    var r0 RecordUsageResponse
    if err := a.Call(
        a.CanisterId,
        "record_usage",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetUsage calls the "get_usage" method on the "backend" canister.
func (a BackendAgent) GetUsage(arg0 GetUsageRequest) (*GetUsageResponse, error) {
    var r0 GetUsageResponse
    if err := a.Query(
        a.CanisterId,
        "get_usage",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminListUserProfiles calls the "admin_list_user_profiles" method on the "backend" canister.
func (a BackendAgent) AdminListUserProfiles() (*ListUserProfilesResponse, error) {
    var r0 ListUserProfilesResponse
    if err := a.Query(
        a.CanisterId,
        "admin_list_user_profiles",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetUserProfilesByPrincipals calls the "get_user_profiles_by_principals" method on the "backend" canister.
func (a BackendAgent) GetUserProfilesByPrincipals(arg0 GetUserProfilesByPrincipalsRequest) (*GetUserProfilesByPrincipalsResponse, error) {
    var r0 GetUserProfilesByPrincipalsResponse
    if err := a.Query(
        a.CanisterId,
        "get_user_profiles_by_principals",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetUserProfilesByUserIds calls the "get_user_profiles_by_user_ids" method on the "backend" canister.
func (a BackendAgent) GetUserProfilesByUserIds(arg0 GetUserProfilesByUserIdsRequest) (*GetUserProfilesByUserIdsResponse, error) {
    var r0 GetUserProfilesByUserIdsResponse
    if err := a.Query(
        a.CanisterId,
        "get_user_profiles_by_user_ids",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminUpdateUserProfile calls the "admin_update_user_profile" method on the "backend" canister.
func (a BackendAgent) AdminUpdateUserProfile(arg0 UpdateUserProfileRequest) (*UpdateUserProfileResponse, error) {
    var r0 UpdateUserProfileResponse
    if err := a.Call(
        a.CanisterId,
        "admin_update_user_profile",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminGetUserStats calls the "admin_get_user_stats" method on the "backend" canister.
func (a BackendAgent) AdminGetUserStats() (*GetUserStatsResponse, error) {
    var r0 GetUserStatsResponse
    if err := a.Query(
        a.CanisterId,
        "admin_get_user_stats",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminListStaleUsers calls the "admin_list_stale_users" method on the "backend" canister.
func (a BackendAgent) AdminListStaleUsers() (*ListStaleUsersResponse, error) {
    var r0 ListStaleUsersResponse
    if err := a.Query(
        a.CanisterId,
        "admin_list_stale_users",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetMyUserProfile calls the "get_my_user_profile" method on the "backend" canister.
func (a BackendAgent) GetMyUserProfile() (*GetMyUserProfileResponse, error) {
    var r0 GetMyUserProfileResponse
    if err := a.Query(
        a.CanisterId,
        "get_my_user_profile",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// CreateMyUserProfile calls the "create_my_user_profile" method on the "backend" canister.
func (a BackendAgent) CreateMyUserProfile() (*CreateMyUserProfileResponse, error) {
    var r0 CreateMyUserProfileResponse
    if err := a.Call(
        a.CanisterId,
        "create_my_user_profile",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// UpdateMyUserProfile calls the "update_my_user_profile" method on the "backend" canister.
func (a BackendAgent) UpdateMyUserProfile(arg0 UpdateMyUserProfileRequest) (*UpdateMyUserProfileResponse, error) {
    var r0 UpdateMyUserProfileResponse
    if err := a.Call(
        a.CanisterId,
        "update_my_user_profile",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// VerifyMyEmail calls the "verify_my_email" method on the "backend" canister.
func (a BackendAgent) VerifyMyEmail(arg0 VerifyEmailRequest) (*VerifyEmailResponse, error) {
    var r0 VerifyEmailResponse
    if err := a.Call(
        a.CanisterId,
        "verify_my_email",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminListTrustedPartners calls the "admin_list_trusted_partners" method on the "backend" canister.
func (a BackendAgent) AdminListTrustedPartners() (*ListTrustedPartnersResponse, error) {
    var r0 ListTrustedPartnersResponse
    if err := a.Query(
        a.CanisterId,
        "admin_list_trusted_partners",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminCreateTrustedPartner calls the "admin_create_trusted_partner" method on the "backend" canister.
func (a BackendAgent) AdminCreateTrustedPartner(arg0 CreateTrustedPartnerRequest) (*CreateTrustedPartnerResponse, error) {
    var r0 CreateTrustedPartnerResponse
    if err := a.Call(
        a.CanisterId,
        "admin_create_trusted_partner",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetLatestTermsAndConditions calls the "get_latest_terms_and_conditions" method on the "backend" canister.
func (a BackendAgent) GetLatestTermsAndConditions() (*GetLatestTermsAndConditionsResponse, error) {
    var r0 GetLatestTermsAndConditionsResponse
    if err := a.Query(
        a.CanisterId,
        "get_latest_terms_and_conditions",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminListTermsAndConditions calls the "admin_list_terms_and_conditions" method on the "backend" canister.
func (a BackendAgent) AdminListTermsAndConditions() (*ListTermsAndConditionsResponse, error) {
    var r0 ListTermsAndConditionsResponse
    if err := a.Query(
        a.CanisterId,
        "admin_list_terms_and_conditions",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// UpsertTermsAndConditionsDecision calls the "upsert_terms_and_conditions_decision" method on the "backend" canister.
func (a BackendAgent) UpsertTermsAndConditionsDecision(arg0 UpsertTermsAndConditionsDecisionRequest) (*UpsertTermsAndConditionsDecisionResponse, error) {
    var r0 UpsertTermsAndConditionsDecisionResponse
    if err := a.Call(
        a.CanisterId,
        "upsert_terms_and_conditions_decision",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminCreateTermsAndConditions calls the "admin_create_terms_and_conditions" method on the "backend" canister.
func (a BackendAgent) AdminCreateTermsAndConditions(arg0 CreateTermsAndConditionsRequest) (*CreateTermsAndConditionsResponse, error) {
    var r0 CreateTermsAndConditionsResponse
    if err := a.Call(
        a.CanisterId,
        "admin_create_terms_and_conditions",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListMyTeams calls the "list_my_teams" method on the "backend" canister.
func (a BackendAgent) ListMyTeams() (*ListTeamsResponse, error) {
    var r0 ListTeamsResponse
    if err := a.Query(
        a.CanisterId,
        "list_my_teams",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListOrgTeams calls the "list_org_teams" method on the "backend" canister.
func (a BackendAgent) ListOrgTeams(arg0 ListOrgTeamsRequest) (*ListOrgTeamsResponse, error) {
    var r0 ListOrgTeamsResponse
    if err := a.Query(
        a.CanisterId,
        "list_org_teams",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListProjectTeams calls the "list_project_teams" method on the "backend" canister.
func (a BackendAgent) ListProjectTeams(arg0 ListProjectTeamsRequest) (*ListProjectTeamsResponse, error) {
    var r0 ListProjectTeamsResponse
    if err := a.Query(
        a.CanisterId,
        "list_project_teams",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// CreateTeam calls the "create_team" method on the "backend" canister.
func (a BackendAgent) CreateTeam(arg0 CreateTeamRequest) (*CreateTeamResponse, error) {
    var r0 CreateTeamResponse
    if err := a.Call(
        a.CanisterId,
        "create_team",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetTeam calls the "get_team" method on the "backend" canister.
func (a BackendAgent) GetTeam(arg0 GetTeamRequest) (*GetTeamResponse, error) {
    var r0 GetTeamResponse
    if err := a.Query(
        a.CanisterId,
        "get_team",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// UpdateTeam calls the "update_team" method on the "backend" canister.
func (a BackendAgent) UpdateTeam(arg0 UpdateTeamRequest) (*UpdateTeamResponse, error) {
    var r0 UpdateTeamResponse
    if err := a.Call(
        a.CanisterId,
        "update_team",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// DeleteTeam calls the "delete_team" method on the "backend" canister.
func (a BackendAgent) DeleteTeam(arg0 DeleteTeamRequest) (*DeleteTeamResponse, error) {
    var r0 DeleteTeamResponse
    if err := a.Call(
        a.CanisterId,
        "delete_team",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AddUserToTeam calls the "add_user_to_team" method on the "backend" canister.
func (a BackendAgent) AddUserToTeam(arg0 AddUserToTeamRequest) (*AddUserToTeamResponse, error) {
    var r0 AddUserToTeamResponse
    if err := a.Call(
        a.CanisterId,
        "add_user_to_team",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// RemoveUserFromTeam calls the "remove_user_from_team" method on the "backend" canister.
func (a BackendAgent) RemoveUserFromTeam(arg0 RemoveUserFromTeamRequest) (*RemoveUserFromTeamResponse, error) {
    var r0 RemoveUserFromTeamResponse
    if err := a.Call(
        a.CanisterId,
        "remove_user_from_team",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListTeamUsers calls the "list_team_users" method on the "backend" canister.
func (a BackendAgent) ListTeamUsers(arg0 ListTeamUsersRequest) (*ListTeamUsersResponse, error) {
    var r0 ListTeamUsersResponse
    if err := a.Query(
        a.CanisterId,
        "list_team_users",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// UpdateTeamOrgPermissions calls the "update_team_org_permissions" method on the "backend" canister.
func (a BackendAgent) UpdateTeamOrgPermissions(arg0 UpdateTeamOrgPermissionsRequest) (*UpdateTeamOrgPermissionsResponse, error) {
    var r0 UpdateTeamOrgPermissionsResponse
    if err := a.Call(
        a.CanisterId,
        "update_team_org_permissions",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetMyStaffPermissions calls the "get_my_staff_permissions" method on the "backend" canister.
func (a BackendAgent) GetMyStaffPermissions(arg0 GetMyStaffPermissionsRequest) (*GetMyStaffPermissionsResponse, error) {
    var r0 GetMyStaffPermissionsResponse
    if err := a.Query(
        a.CanisterId,
        "get_my_staff_permissions",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminGrantStaffPermissions calls the "admin_grant_staff_permissions" method on the "backend" canister.
func (a BackendAgent) AdminGrantStaffPermissions(arg0 GrantStaffPermissionsRequest) (*GrantStaffPermissionsResponse, error) {
    var r0 GrantStaffPermissionsResponse
    if err := a.Call(
        a.CanisterId,
        "admin_grant_staff_permissions",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminRevokeStaffPermissions calls the "admin_revoke_staff_permissions" method on the "backend" canister.
func (a BackendAgent) AdminRevokeStaffPermissions(arg0 RevokeStaffPermissionsRequest) (*RevokeStaffPermissionsResponse, error) {
    var r0 RevokeStaffPermissionsResponse
    if err := a.Call(
        a.CanisterId,
        "admin_revoke_staff_permissions",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminListStaff calls the "admin_list_staff" method on the "backend" canister.
func (a BackendAgent) AdminListStaff(arg0 ListStaffRequest) (*ListStaffResponse, error) {
    var r0 ListStaffResponse
    if err := a.Query(
        a.CanisterId,
        "admin_list_staff",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminGrantServicePrincipalPermissions calls the "admin_grant_service_principal_permissions" method on the "backend" canister.
func (a BackendAgent) AdminGrantServicePrincipalPermissions(arg0 GrantServicePrincipalPermissionsRequest) (*GrantServicePrincipalPermissionsResponse, error) {
    var r0 GrantServicePrincipalPermissionsResponse
    if err := a.Call(
        a.CanisterId,
        "admin_grant_service_principal_permissions",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminRevokeServicePrincipalPermissions calls the "admin_revoke_service_principal_permissions" method on the "backend" canister.
func (a BackendAgent) AdminRevokeServicePrincipalPermissions(arg0 RevokeServicePrincipalPermissionsRequest) (*RevokeServicePrincipalPermissionsResponse, error) {
    var r0 RevokeServicePrincipalPermissionsResponse
    if err := a.Call(
        a.CanisterId,
        "admin_revoke_service_principal_permissions",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminListServicePrincipals calls the "admin_list_service_principals" method on the "backend" canister.
func (a BackendAgent) AdminListServicePrincipals(arg0 ListServicePrincipalsRequest) (*ListServicePrincipalsResponse, error) {
    var r0 ListServicePrincipalsResponse
    if err := a.Query(
        a.CanisterId,
        "admin_list_service_principals",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// CreateProposal calls the "create_proposal" method on the "backend" canister.
func (a BackendAgent) CreateProposal(arg0 CreateProposalRequest) (*CreateProposalResponse, error) {
    var r0 CreateProposalResponse
    if err := a.Call(
        a.CanisterId,
        "create_proposal",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetProposal calls the "get_proposal" method on the "backend" canister.
func (a BackendAgent) GetProposal(arg0 GetProposalRequest) (*GetProposalResponse, error) {
    var r0 GetProposalResponse
    if err := a.Query(
        a.CanisterId,
        "get_proposal",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListProjectProposals calls the "list_project_proposals" method on the "backend" canister.
func (a BackendAgent) ListProjectProposals(arg0 ListProjectProposalsRequest) (*ListProjectProposalsResponse, error) {
    var r0 ListProjectProposalsResponse
    if err := a.Query(
        a.CanisterId,
        "list_project_proposals",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// VoteProposal calls the "vote_proposal" method on the "backend" canister.
func (a BackendAgent) VoteProposal(arg0 VoteProposalRequest) (*VoteProposalResponse, error) {
    var r0 VoteProposalResponse
    if err := a.Call(
        a.CanisterId,
        "vote_proposal",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// CancelProposal calls the "cancel_proposal" method on the "backend" canister.
func (a BackendAgent) CancelProposal(arg0 CancelProposalRequest) (*CancelProposalResponse, error) {
    var r0 CancelProposalResponse
    if err := a.Call(
        a.CanisterId,
        "cancel_proposal",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListMyProjects calls the "list_my_projects" method on the "backend" canister.
func (a BackendAgent) ListMyProjects(arg0 ListMyProjectsRequest) (*ListMyProjectsResponse, error) {
    var r0 ListMyProjectsResponse
    if err := a.Query(
        a.CanisterId,
        "list_my_projects",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListOrgProjects calls the "list_org_projects" method on the "backend" canister.
func (a BackendAgent) ListOrgProjects(arg0 ListOrgProjectsRequest) (*ListOrgProjectsResponse, error) {
    var r0 ListOrgProjectsResponse
    if err := a.Query(
        a.CanisterId,
        "list_org_projects",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// CreateProject calls the "create_project" method on the "backend" canister.
func (a BackendAgent) CreateProject(arg0 CreateProjectRequest) (*CreateProjectResponse, error) {
    var r0 CreateProjectResponse
    if err := a.Call(
        a.CanisterId,
        "create_project",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetProject calls the "get_project" method on the "backend" canister.
func (a BackendAgent) GetProject(arg0 GetProjectRequest) (*GetProjectResponse, error) {
    var r0 GetProjectResponse
    if err := a.Query(
        a.CanisterId,
        "get_project",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// UpdateProject calls the "update_project" method on the "backend" canister.
func (a BackendAgent) UpdateProject(arg0 UpdateProjectRequest) (*UpdateProjectResponse, error) {
    var r0 UpdateProjectResponse
    if err := a.Call(
        a.CanisterId,
        "update_project",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// DeleteProject calls the "delete_project" method on the "backend" canister.
func (a BackendAgent) DeleteProject(arg0 DeleteProjectRequest) (*DeleteProjectResponse, error) {
    var r0 DeleteProjectResponse
    if err := a.Call(
        a.CanisterId,
        "delete_project",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AddTeamToProject calls the "add_team_to_project" method on the "backend" canister.
func (a BackendAgent) AddTeamToProject(arg0 AddTeamToProjectRequest) (*AddTeamToProjectResponse, error) {
    var r0 AddTeamToProjectResponse
    if err := a.Call(
        a.CanisterId,
        "add_team_to_project",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// RemoveTeamFromProject calls the "remove_team_from_project" method on the "backend" canister.
func (a BackendAgent) RemoveTeamFromProject(arg0 RemoveTeamFromProjectRequest) (*RemoveTeamFromProjectResponse, error) {
    var r0 RemoveTeamFromProjectResponse
    if err := a.Call(
        a.CanisterId,
        "remove_team_from_project",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// UpdateTeamProjectPermissions calls the "update_team_project_permissions" method on the "backend" canister.
func (a BackendAgent) UpdateTeamProjectPermissions(arg0 UpdateTeamProjectPermissionsRequest) (*UpdateTeamProjectPermissionsResponse, error) {
    var r0 UpdateTeamProjectPermissionsResponse
    if err := a.Call(
        a.CanisterId,
        "update_team_project_permissions",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// RegisterLinkCode calls the "register_link_code" method on the "backend" canister.
func (a BackendAgent) RegisterLinkCode(arg0 RegisterLinkCodeRequest) (*RegisterLinkCodeResponse, error) {
    var r0 RegisterLinkCodeResponse
    if err := a.Call(
        a.CanisterId,
        "register_link_code",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// LinkMyPrincipal calls the "link_my_principal" method on the "backend" canister.
func (a BackendAgent) LinkMyPrincipal(arg0 LinkMyPrincipalRequest) (*LinkMyPrincipalResponse, error) {
    var r0 LinkMyPrincipalResponse
    if err := a.Call(
        a.CanisterId,
        "link_my_principal",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// UnlinkMyPrincipal calls the "unlink_my_principal" method on the "backend" canister.
func (a BackendAgent) UnlinkMyPrincipal(arg0 UnlinkMyPrincipalRequest) (*UnlinkMyPrincipalResponse, error) {
    var r0 UnlinkMyPrincipalResponse
    if err := a.Call(
        a.CanisterId,
        "unlink_my_principal",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListMyLinkedPrincipals calls the "list_my_linked_principals" method on the "backend" canister.
func (a BackendAgent) ListMyLinkedPrincipals(arg0 ListMyLinkedPrincipalsRequest) (*ListMyLinkedPrincipalsResponse, error) {
    var r0 ListMyLinkedPrincipalsResponse
    if err := a.Query(
        a.CanisterId,
        "list_my_linked_principals",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetMyPendingLinkCode calls the "get_my_pending_link_code" method on the "backend" canister.
func (a BackendAgent) GetMyPendingLinkCode(arg0 GetMyPendingLinkCodeRequest) (*GetMyPendingLinkCodeResponse, error) {
    var r0 GetMyPendingLinkCodeResponse
    if err := a.Query(
        a.CanisterId,
        "get_my_pending_link_code",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// RevokeMyLinkCode calls the "revoke_my_link_code" method on the "backend" canister.
func (a BackendAgent) RevokeMyLinkCode(arg0 RevokeMyLinkCodeRequest) (*RevokeMyLinkCodeResponse, error) {
    var r0 RevokeMyLinkCodeResponse
    if err := a.Call(
        a.CanisterId,
        "revoke_my_link_code",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// SetMyPrincipalName calls the "set_my_principal_name" method on the "backend" canister.
func (a BackendAgent) SetMyPrincipalName(arg0 SetMyPrincipalNameRequest) (*SetMyPrincipalNameResponse, error) {
    var r0 SetMyPrincipalNameResponse
    if err := a.Call(
        a.CanisterId,
        "set_my_principal_name",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminLinkPrincipalToUser calls the "admin_link_principal_to_user" method on the "backend" canister.
func (a BackendAgent) AdminLinkPrincipalToUser(arg0 AdminLinkPrincipalRequest) (*AdminLinkPrincipalResponse, error) {
    var r0 AdminLinkPrincipalResponse
    if err := a.Call(
        a.CanisterId,
        "admin_link_principal_to_user",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminUnlinkPrincipalFromUser calls the "admin_unlink_principal_from_user" method on the "backend" canister.
func (a BackendAgent) AdminUnlinkPrincipalFromUser(arg0 AdminUnlinkPrincipalRequest) (*AdminUnlinkPrincipalResponse, error) {
    var r0 AdminUnlinkPrincipalResponse
    if err := a.Call(
        a.CanisterId,
        "admin_unlink_principal_from_user",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminListLinkedPrincipals calls the "admin_list_linked_principals" method on the "backend" canister.
func (a BackendAgent) AdminListLinkedPrincipals(arg0 AdminListLinkedPrincipalsRequest) (*AdminListLinkedPrincipalsResponse, error) {
    var r0 AdminListLinkedPrincipalsResponse
    if err := a.Query(
        a.CanisterId,
        "admin_list_linked_principals",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// RecoverAccountByEmail calls the "recover_account_by_email" method on the "backend" canister.
func (a BackendAgent) RecoverAccountByEmail(arg0 RecoverAccountByEmailRequest) (*RecoverAccountByEmailResponse, error) {
    var r0 RecoverAccountByEmailResponse
    if err := a.Call(
        a.CanisterId,
        "recover_account_by_email",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminSetOrgBillingPlan calls the "admin_set_org_billing_plan" method on the "backend" canister.
func (a BackendAgent) AdminSetOrgBillingPlan(arg0 SetOrgBillingPlanRequest) (*SetOrgBillingPlanResponse, error) {
    var r0 SetOrgBillingPlanResponse
    if err := a.Call(
        a.CanisterId,
        "admin_set_org_billing_plan",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetOrgBillingPlan calls the "get_org_billing_plan" method on the "backend" canister.
func (a BackendAgent) GetOrgBillingPlan(arg0 GetOrgBillingPlanRequest) (*GetOrgBillingPlanResponse, error) {
    var r0 GetOrgBillingPlanResponse
    if err := a.Query(
        a.CanisterId,
        "get_org_billing_plan",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListMyOrgBillingPlans calls the "list_my_org_billing_plans" method on the "backend" canister.
func (a BackendAgent) ListMyOrgBillingPlans() (*ListMyOrgBillingPlansResponse, error) {
    var r0 ListMyOrgBillingPlansResponse
    if err := a.Query(
        a.CanisterId,
        "list_my_org_billing_plans",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListMyOrganizations calls the "list_my_organizations" method on the "backend" canister.
func (a BackendAgent) ListMyOrganizations() (*ListMyOrganizationsResponse, error) {
    var r0 ListMyOrganizationsResponse
    if err := a.Query(
        a.CanisterId,
        "list_my_organizations",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminListOrganizations calls the "admin_list_organizations" method on the "backend" canister.
func (a BackendAgent) AdminListOrganizations(arg0 ListOrganizationsRequest) (*ListOrganizationsResponse, error) {
    var r0 ListOrganizationsResponse
    if err := a.Query(
        a.CanisterId,
        "admin_list_organizations",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// CreateOrganization calls the "create_organization" method on the "backend" canister.
func (a BackendAgent) CreateOrganization(arg0 CreateOrganizationRequest) (*CreateOrganizationResponse, error) {
    var r0 CreateOrganizationResponse
    if err := a.Call(
        a.CanisterId,
        "create_organization",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// GetOrganization calls the "get_organization" method on the "backend" canister.
func (a BackendAgent) GetOrganization(arg0 GetOrganizationRequest) (*GetOrganizationResponse, error) {
    var r0 GetOrganizationResponse
    if err := a.Query(
        a.CanisterId,
        "get_organization",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// UpdateOrganization calls the "update_organization" method on the "backend" canister.
func (a BackendAgent) UpdateOrganization(arg0 UpdateOrganizationRequest) (*UpdateOrganizationResponse, error) {
    var r0 UpdateOrganizationResponse
    if err := a.Call(
        a.CanisterId,
        "update_organization",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// DeleteOrganization calls the "delete_organization" method on the "backend" canister.
func (a BackendAgent) DeleteOrganization(arg0 DeleteOrganizationRequest) (*DeleteOrganizationResponse, error) {
    var r0 DeleteOrganizationResponse
    if err := a.Call(
        a.CanisterId,
        "delete_organization",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListOrgUsers calls the "list_org_users" method on the "backend" canister.
func (a BackendAgent) ListOrgUsers(arg0 ListOrgUsersRequest) (*ListOrgUsersResponse, error) {
    var r0 ListOrgUsersResponse
    if err := a.Query(
        a.CanisterId,
        "list_org_users",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminGetMetrics calls the "admin_get_metrics" method on the "backend" canister.
func (a BackendAgent) AdminGetMetrics(arg0 GetMetricsRequest) (*GetMetricsResponse, error) {
    var r0 GetMetricsResponse
    if err := a.Query(
        a.CanisterId,
        "admin_get_metrics",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// CreateOrgInvite calls the "create_org_invite" method on the "backend" canister.
func (a BackendAgent) CreateOrgInvite(arg0 CreateOrgInviteRequest) (*CreateOrgInviteResponse, error) {
    var r0 CreateOrgInviteResponse
    if err := a.Call(
        a.CanisterId,
        "create_org_invite",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListOrgInvites calls the "list_org_invites" method on the "backend" canister.
func (a BackendAgent) ListOrgInvites(arg0 ListOrgInvitesRequest) (*ListOrgInvitesResponse, error) {
    var r0 ListOrgInvitesResponse
    if err := a.Query(
        a.CanisterId,
        "list_org_invites",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// RevokeOrgInvite calls the "revoke_org_invite" method on the "backend" canister.
func (a BackendAgent) RevokeOrgInvite(arg0 RevokeOrgInviteRequest) (*RevokeOrgInviteResponse, error) {
    var r0 RevokeOrgInviteResponse
    if err := a.Call(
        a.CanisterId,
        "revoke_org_invite",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListMyInvites calls the "list_my_invites" method on the "backend" canister.
func (a BackendAgent) ListMyInvites() (*ListMyInvitesResponse, error) {
    var r0 ListMyInvitesResponse
    if err := a.Query(
        a.CanisterId,
        "list_my_invites",
        []any{},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AcceptOrgInvite calls the "accept_org_invite" method on the "backend" canister.
func (a BackendAgent) AcceptOrgInvite(arg0 AcceptOrgInviteRequest) (*AcceptOrgInviteResponse, error) {
    var r0 AcceptOrgInviteResponse
    if err := a.Call(
        a.CanisterId,
        "accept_org_invite",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// DeclineOrgInvite calls the "decline_org_invite" method on the "backend" canister.
func (a BackendAgent) DeclineOrgInvite(arg0 DeclineOrgInviteRequest) (*DeclineOrgInviteResponse, error) {
    var r0 DeclineOrgInviteResponse
    if err := a.Call(
        a.CanisterId,
        "decline_org_invite",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// HttpRequest calls the "http_request" method on the "backend" canister.
func (a BackendAgent) HttpRequest(arg0 HttpRequest) (*HttpResponse, error) {
    var r0 HttpResponse
    if err := a.Query(
        a.CanisterId,
        "http_request",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// CreateCanister calls the "create_canister" method on the "backend" canister.
func (a BackendAgent) CreateCanister(arg0 CreateCanisterArgs) (*struct {
	Ok  *CreateCanisterSuccess `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *CreateCanisterError   `ic:"Err,variant" json:"Err,omitempty"`
}, error) {
    var r0 struct {
	Ok  *CreateCanisterSuccess `ic:"Ok,variant" json:"Ok,omitempty"`
	Err *CreateCanisterError   `ic:"Err,variant" json:"Err,omitempty"`
}
    if err := a.Call(
        a.CanisterId,
        "create_canister",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListMyCanisters calls the "list_my_canisters" method on the "backend" canister.
func (a BackendAgent) ListMyCanisters(arg0 ListMyCanistersRequest) (*ListMyCanistersResponse, error) {
    var r0 ListMyCanistersResponse
    if err := a.Call(
        a.CanisterId,
        "list_my_canisters",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminListUserCanisters calls the "admin_list_user_canisters" method on the "backend" canister.
func (a BackendAgent) AdminListUserCanisters(arg0 ListUserCanistersRequest) (*ListUserCanistersResponse, error) {
    var r0 ListUserCanistersResponse
    if err := a.Call(
        a.CanisterId,
        "admin_list_user_canisters",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// RemoveMyCanister calls the "remove_my_canister" method on the "backend" canister.
func (a BackendAgent) RemoveMyCanister(arg0 RemoveMyCanisterRequest) (*RemoveMyCanisterResponse, error) {
    var r0 RemoveMyCanisterResponse
    if err := a.Call(
        a.CanisterId,
        "remove_my_canister",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// UpdateMyCanisterName calls the "update_my_canister_name" method on the "backend" canister.
func (a BackendAgent) UpdateMyCanisterName(arg0 UpdateMyCanisterNameRequest) (*UpdateMyCanisterNameResponse, error) {
    var r0 UpdateMyCanisterNameResponse
    if err := a.Call(
        a.CanisterId,
        "update_my_canister_name",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// StartMyCanister calls the "start_my_canister" method on the "backend" canister.
func (a BackendAgent) StartMyCanister(arg0 StartMyCanisterRequest) (*StartMyCanisterResponse, error) {
    var r0 StartMyCanisterResponse
    if err := a.Call(
        a.CanisterId,
        "start_my_canister",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// StopMyCanister calls the "stop_my_canister" method on the "backend" canister.
func (a BackendAgent) StopMyCanister(arg0 StopMyCanisterRequest) (*StopMyCanisterResponse, error) {
    var r0 StopMyCanisterResponse
    if err := a.Call(
        a.CanisterId,
        "stop_my_canister",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminListUserReadableCanisterPrincipals calls the "admin_list_user_readable_canister_principals" method on the "backend" canister.
func (a BackendAgent) AdminListUserReadableCanisterPrincipals(arg0 ListUserReadableCanisterPrincipalsRequest) (*ListUserReadableCanisterPrincipalsResponse, error) {
    var r0 ListUserReadableCanisterPrincipalsResponse
    if err := a.Query(
        a.CanisterId,
        "admin_list_user_readable_canister_principals",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AdminListAllCanisters calls the "admin_list_all_canisters" method on the "backend" canister.
func (a BackendAgent) AdminListAllCanisters(arg0 ListAllCanistersRequest) (*ListAllCanistersResponse, error) {
    var r0 ListAllCanistersResponse
    if err := a.Query(
        a.CanisterId,
        "admin_list_all_canisters",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// AddChildCanisters calls the "add_child_canisters" method on the "backend" canister.
func (a BackendAgent) AddChildCanisters(arg0 AddChildCanistersRequest) (*TrackChildCanistersResponse, error) {
    var r0 TrackChildCanistersResponse
    if err := a.Call(
        a.CanisterId,
        "add_child_canisters",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// ListProjectApprovalPolicies calls the "list_project_approval_policies" method on the "backend" canister.
func (a BackendAgent) ListProjectApprovalPolicies(arg0 ListProjectApprovalPoliciesRequest) (*ListProjectApprovalPoliciesResponse, error) {
    var r0 ListProjectApprovalPoliciesResponse
    if err := a.Query(
        a.CanisterId,
        "list_project_approval_policies",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}

// UpsertApprovalPolicy calls the "upsert_approval_policy" method on the "backend" canister.
func (a BackendAgent) UpsertApprovalPolicy(arg0 UpsertApprovalPolicyRequest) (*UpsertApprovalPolicyResponse, error) {
    var r0 UpsertApprovalPolicyResponse
    if err := a.Call(
        a.CanisterId,
        "upsert_approval_policy",
        []any{arg0},
        []any{&r0},
    ); err != nil {
        return nil, err
    }
    return &r0, nil
}
