#!/bin/bash
set -euo pipefail

# Start from repository root
ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

CANISTERS=(backend canister-history cycles-monitor)

echo
echo "Stopping any running local network..."
icp network stop || true

echo
echo "Starting local network..."
icp network start -d

echo
echo "Creating canisters..."
# Create + build separately from install so dynamic env vars (secret +
# cross-canister ids) can be set before install; post_upgrade reads them eagerly.
for c in "${CANISTERS[@]}"; do
  icp canister create "$c" -e local
done

echo
echo "Building canisters..."
icp build -e local

echo
echo "Setting canister environment variables..."
# Apply static settings from icp.yaml first, then merge the dynamic vars on top.
for c in "${CANISTERS[@]}"; do
  icp canister settings sync "$c" -e local
done
./scripts/set-canister-env.sh

echo
echo "Installing canisters..."
for c in "${CANISTERS[@]}"; do
  icp canister install "$c" -e local -y
done

echo
echo "Writing .env for the frontend..."
# icp-cli has no output_env_file; the frontend's vite build reads ids from .env.
cat > .env <<EOF
# Generated by scripts/init-local.sh from icp-cli canister ids. Do not edit.
DFX_NETWORK='local'
CANISTER_ID_BACKEND='$(icp canister status backend -e local --id-only)'
CANISTER_ID_CANISTER_HISTORY='$(icp canister status canister-history -e local --id-only)'
CANISTER_ID_CYCLES_MONITOR='$(icp canister status cycles-monitor -e local --id-only)'
EOF

./scripts/update-local-history-ranges.sh

echo
echo "Triggering canister-history sync..."
icp canister call canister-history trigger_sync_canister_histories '(record {})' -e local

echo
echo "Local environment ready."
