#!/bin/bash
set -euo pipefail

# Start from repository root
ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

CANISTERS=(backend canister-history cycles-monitor)

# The backend reads DFX_NETWORK via dotenv! at compile time, so .env must exist
# before `icp build`. Seed it; the full version (with canister ids) is written
# after install below.
echo "DFX_NETWORK='local'" > .env

echo
echo "Stopping any running local network..."
icp network stop || true

echo
echo "Starting local network..."
icp network start -d

echo
echo "Creating canisters..."
# Create + build separately from install so dynamic env vars (secret +
# cross-canister ids) can be set before install; post_upgrade reads them eagerly.
for c in "${CANISTERS[@]}"; do
  icp canister create "$c" -e local
done

# The rental subnet admin in icp.yaml is hardcoded (set at network start, before
# canisters exist). Fail loudly if the real cycles-monitor id drifts from it,
# else canister_metrics is silently unauthorized and no snapshots are stored.
CM_ID="$(icp canister status cycles-monitor -e local --id-only)"
RENTAL_ADMIN="$(grep -oE 'application:rental=[a-z0-9-]+' icp.yaml | cut -d= -f2)"
if [ "$CM_ID" != "$RENTAL_ADMIN" ]; then
  echo "init-local: cycles-monitor id ($CM_ID) != rental admin in icp.yaml ($RENTAL_ADMIN)." >&2
  echo "            Update the --subnet=application:rental= principal in icp.yaml." >&2
  exit 1
fi

echo
echo "Building canisters..."
icp build -e local

echo
echo "Setting canister environment variables..."
# Apply static settings from icp.yaml first, then merge the dynamic vars on top.
for c in "${CANISTERS[@]}"; do
  icp canister settings sync "$c" -e local
done
./scripts/set-canister-env.sh

echo
echo "Installing canisters..."
for c in "${CANISTERS[@]}"; do
  icp canister install "$c" -e local -y
done

echo
echo "Granting admin to the RFC 8032 test identity (ssn-admin CLI / local tooling)..."
# Backend admin == canister controller (assert_staff_perm short-circuits on
# is_controller). Add the RFC 8032 Test 1 principal -- the identity ssn-admin
# authenticates as locally -- so the CLI has admin without exporting icp's key.
TEST_VECTOR_PRINCIPAL="e73il-iz5tp-nkgt7-idxyw-ngkah-47bpv-qdase-pzde6-g6vwc-a3eql-jae"
icp canister settings update backend -e local --add-controller "$TEST_VECTOR_PRINCIPAL"

echo
echo "Writing .env for the frontend..."
# icp-cli has no output_env_file; the frontend's vite build reads ids from .env.
cat > .env <<EOF
# Generated by scripts/init-local.sh from icp-cli canister ids. Do not edit.
DFX_NETWORK='local'
CANISTER_ID_BACKEND='$(icp canister status backend -e local --id-only)'
CANISTER_ID_CANISTER_HISTORY='$(icp canister status canister-history -e local --id-only)'
CANISTER_ID_CYCLES_MONITOR='$(icp canister status cycles-monitor -e local --id-only)'
EOF

./scripts/update-local-history-ranges.sh

echo
echo "Triggering canister-history sync..."
icp canister call canister-history trigger_sync_canister_histories '(record {})' -e local

echo
echo "Waiting for canister-history to populate, then triggering cycles-monitor sync..."
# The history sync is async; cycles-monitor's metrics walk needs it populated.
for _ in $(seq 1 20); do
  if icp canister call canister-history list_subnet_canister_ids '(record {})' -e local 2>/dev/null | grep -q principal; then
    break
  fi
  sleep 1
done
icp canister call cycles-monitor trigger_sync_metrics '(record {})' -e local

echo
echo "Registering Internet Identity custom domain (id.ai.localhost)..."
# icp-cli only writes the id.ai.localhost gateway route for Launcher-mode networks;
# our Image-mode --ii is invisible to it. Append after installs (which rewrite the
# file from scratch); the gateway's file provider re-reads it live.
STATUS_DIR="$(jq -r '.["status-dir"] // empty' .icp/cache/networks/local/descriptor.json 2>/dev/null)"
if [ -n "$STATUS_DIR" ] && [ -f "$STATUS_DIR/custom-domains.txt" ]; then
  grep -q "^id.ai.localhost:" "$STATUS_DIR/custom-domains.txt" ||
    echo "id.ai.localhost:uqzsh-gqaaa-aaaaq-qaada-cai" >> "$STATUS_DIR/custom-domains.txt"
else
  echo "init-local: custom-domains.txt not found; II login domain not registered." >&2
fi

echo
echo "Local environment ready."
