name: Build and Test

on:
  pull_request:

concurrency:
  group: pr-${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_and_test_all_canisters:
    name: Build and Test All Canisters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup DFX
        uses: ./.github/actions/setup-dfx

      - name: DFX build
        run: dfx build --check

      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features

      - name: Cargo test
        run: cargo test

  build_and_test_backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup DFX
        uses: ./.github/actions/setup-dfx

      - name: DFX build
        run: dfx build backend --check

      - name: pic-js tests
        run: bun turbo run -F backend-tests test

  build_and_test_canister_history:
    name: Build and Test Canister History
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup DFX
        uses: ./.github/actions/setup-dfx

      - name: DFX build
        run: dfx build canister-history --check

      - name: pic-js tests
        run: bun turbo run -F canister-history-tests test

  build_and_test_cycles_monitor:
    name: Build and Test Cycles Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup DFX
        uses: ./.github/actions/setup-dfx

      - name: DFX build
        run: dfx build cycles-monitor --check

      - name: pic-js tests
        run: bun turbo run -F cycles-monitor-tests test

  type_check_typescript:
    name: Type Check TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Build
        run: bun turbo build

      - name: Type check
        run: bun type-check

  build_offchain_service:
    name: Build Offchain Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Container image
        run: docker build -f ./config/offchain-service.containerfile -t offchain-service .

  test_offchain_service:
    name: Test Offchain Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Unit tests
        run: bun turbo run -F offchain-service test
