name: Post Canbench results

on:
  workflow_run:
    workflows: ['Run canister benchmarks']
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dawidd6/action-download-artifact@v8
        with:
          run_id: ${{ github.event.workflow_run.id }}

      - id: build-comment
        run: bash ./scripts/ci-download-canbench-artifacts.sh

      - name: Post comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ${{ steps.build-comment.outputs.comment_file }}
          comment-tag: canbench_results
          pr-number: ${{ steps.build-comment.outputs.pr_number }}
