name: Deploy Test

on:
  push:
    branches:
      - main

concurrency:
  group: test
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://r5rta-kyaaa-aaaax-qaaca-cai.icp0.io
    env:
      DFX_WARNING: -mainnet_plaintext_identity
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup DFX
        uses: ./.github/actions/setup-dfx

      - name: Import DFX Identity
        uses: ./.github/actions/import-dfx-identity
        with:
          identity_pem: ${{ secrets.IDENTITY_PEM }}

      - name: Update backend env vars
        uses: ./.github/actions/update-backend-env-vars
        with:
          network: test
          public_key: ${{ secrets.PUBLIC_KEY }}
          offchain_service_url: ${{ secrets.OFFCHAIN_SERVICE_URL }}

      - name: Deploy to test
        run: dfx deploy --network test
