name: Deploy Production

on: workflow_dispatch

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://console.subnet.ch
    env:
      DFX_WARNING: -mainnet_plaintext_identity
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup DFX
        uses: ./.github/actions/setup-dfx

      - name: Import DFX identity
        run: |
          echo "${{ secrets.IDENTITY_PEM }}" > ./production.pem
          dfx identity import --ic --storage-mode plaintext production ./production.pem
          rm -f ./production.pem
          dfx identity use production

      - name: Update Canister Environment Variables
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        run: |
          BACKEND_ID=$(dfx canister id backend --network production)
          FORMATTED_KEY=$(echo "$PUBLIC_KEY" | awk '{printf "%s\\n", $0}' | sed 's/\\n$//')

          dfx canister call aaaaa-aa update_settings "(
            record {
              canister_id = principal \"$BACKEND_ID\";
              settings = record {
                environment_variables = opt vec {
                  record {
                    name = \"PUBLIC_KEY\";
                    value = \"$FORMATTED_KEY\";
                  };
                };
              };
            }
          )" --network production

      - name: Deploy to production
        run: dfx deploy --network production
