name: Run canister benchmarks

on:
  pull_request:

concurrency:
  group: pr-${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  RUST_VERSION: 1.92.0 # Use the same version as in `rust-toolchain.toml`
  CARGO_TERM_COLOR: always # Force Cargo to use colors
  TERM: xterm-256color

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - canister-history
          - cycles-monitor
        include:
          - name: canister-history
            project_dir: ./benchmarks/canister-history
          - name: cycles-monitor
            project_dir: ./benchmarks/cycles-monitor

    env:
      PROJECT_DIR: ${{ matrix.project_dir }}

    steps:
      - name: Checkout current PR
        uses: actions/checkout@v6

      - name: Checkout baseline branch
        uses: actions/checkout@v6
        with:
          ref: main
          path: _canbench_baseline_branch

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-1

      - name: Install Rust
        run: |
          rustup update ${RUST_VERSION} --no-self-update
          rustup default ${RUST_VERSION}
          rustup target add wasm32-unknown-unknown

      - name: Benchmark
        run: |
          bash ./scripts/ci-run-benchmark.sh $PROJECT_DIR ${{ matrix.name }}

      - uses: actions/upload-artifact@v5
        with:
          name: canbench_result_${{ matrix.name }}
          path: /tmp/canbench_result_${{ matrix.name }}

      - uses: actions/upload-artifact@v5
        with:
          name: canbench_results_persisted_${{ matrix.name }}_yml
          path: /tmp/canbench_results_persisted_${{ matrix.name }}.yml

      - uses: actions/upload-artifact@v5
        with:
          name: canbench_results_${{ matrix.name }}_csv
          path: /tmp/canbench_results_${{ matrix.name }}.csv

      - name: Pass or fail
        run: |
          bash ./scripts/ci-post-run-benchmark.sh
